experiment_config_name: 2025-11-21_00-09-39_MSFT_1h_chronos_base_split_2023-01-01_train_175d_test_1y_horizon_1
run_timestamp: 2025-11-21_00-09-39
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/chronos_base/train-less-year-linear-pct/2025-11-21_00-09-39_MSFT_1h_chronos_base_split_2023-01-01_train_175d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.6054560375583065e-05
  mae: 0.004005297859314027
  rmse: 0.006004544976564258
  mape: 113306680977.96039
  smape: 185.8674494259874
  mean_directional_accuracy: 48.285714285714285
