experiment_config_name: 2025-10-13_11-42-13_MSFT_1h_chronos_base_split_2023-01-01_train_100d_test_1y_horizon_1
run_timestamp: 2025-10-13_11-42-13
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/chronos_base/train-less-year-linear-pct/2025-10-13_11-42-13_MSFT_1h_chronos_base_split_2023-01-01_train_100d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.604111865138905e-05
  mae: 0.004005672722392786
  rmse: 0.006003425576401281
  mape: 149679629092.7756
  smape: 184.63300636256724
  mean_directional_accuracy: 48.68571428571429
