experiment_config_name: 2025-10-11_23-57-42_MSFT_1d_chronos_base_split_2023-01-01_train_25d_test_1y_horizon_21
run_timestamp: 2025-10-11_23-57-42
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-linear-pct/2025-10-11_23-57-42_MSFT_1d_chronos_base_split_2023-01-01_train_25d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026495549069447576
  mae: 0.012398315912974061
  rmse: 0.016277453446238935
  mape: 125.21712424873567
  smape: 163.7078172118871
  mean_directional_accuracy: 50.4
