experiment_config_name: 2025-11-17_15-27-46_MSFT_1d_chronos_base_split_2023-01-01_train_200d_test_1y_horizon_21
run_timestamp: 2025-11-17_15-27-46
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/chronos_base/train-less-year-linear-pct/2025-11-17_15-27-46_MSFT_1d_chronos_base_split_2023-01-01_train_200d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00027492318002747806
  mae: 0.01234065334786144
  rmse: 0.016580807580678272
  mape: 112.18881101348495
  smape: 170.99655441837805
  mean_directional_accuracy: 47.599999999999994
