experiment_config_name: 2025-10-11_23-58-01_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_21
run_timestamp: 2025-10-11_23-58-01
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-linear-pct/2025-10-11_23-58-01_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026079114425978854
  mae: 0.012254148152176573
  rmse: 0.016149029204871372
  mape: 114.52099795316413
  smape: 171.4461610137107
  mean_directional_accuracy: 53.2
