experiment_config_name: 2025-11-17_15-31-23_MSFT_1d_chronos_base_split_2023-01-01_train_225d_test_1y_horizon_63
run_timestamp: 2025-11-17_15-31-23
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 225
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/chronos_base/train-less-year-linear-pct/2025-11-17_15-31-23_MSFT_1d_chronos_base_split_2023-01-01_train_225d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000274176286317549
  mae: 0.01236782966432628
  rmse: 0.016558269423993226
  mape: 111.78197147431933
  smape: 176.87144502654618
  mean_directional_accuracy: 52.800000000000004
