experiment_config_name: 2025-10-12_00-00-15_MSFT_1d_chronos_base_split_2023-01-01_train_200d_test_1y_horizon_63
run_timestamp: 2025-10-12_00-00-15
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-linear-pct/2025-10-12_00-00-15_MSFT_1d_chronos_base_split_2023-01-01_train_200d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026307231719750426
  mae: 0.012346910298790157
  rmse: 0.016219504221692604
  mape: 117.0671017087797
  smape: 177.82525120160065
  mean_directional_accuracy: 47.199999999999996
