experiment_config_name: 2025-11-30_18-06-31_MSFT_1h_fm_split_2008-01-20_train_32d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-06-31
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 32
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/rq3-financial-crisis-2008-log-pct/2025-11-30_18-06-31_MSFT_1h_fm_split_2008-01-20_train_32d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 8.614210430749702e-05
  mae: 0.005946660699053301
  rmse: 0.009281277083866047
  mape: 3944127832776.158
  smape: 159.36916851478134
  mean_directional_accuracy: 52.961672473867594
