experiment_config_name: 2025-07-19_22-29-26_MSFT_1d_sundial_split_2023-01-01_train_2y_test_1y_horizon_63
run_timestamp: 2025-07-19_22-29-26
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
results_file_path: results/train-restricted-years/sundial/MSFT/2025-07-19_22-29-26_MSFT_1d_sundial_split_2023-01-01_train_2y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1302.2769798090353
  mae: 25.208458825880992
  rmse: 36.087074968872656
  mape: 7.5100248179030755
