experiment_config_name: 2025-07-19_22-28-29_MSFT_1d_sundial_split_2023-01-01_train_2y_test_1y_horizon_21
run_timestamp: 2025-07-19_22-28-29
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
results_file_path: results/train-restricted-years/sundial/MSFT/2025-07-19_22-28-29_MSFT_1d_sundial_split_2023-01-01_train_2y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 309.50095639868135
  mae: 12.33995477400493
  rmse: 17.592639267565325
  mape: 3.857718065183287
