experiment_config_name: 2025-07-19_22-29-34_MSFT_1d_sundial_split_2023-01-01_train_4y_test_1y_horizon_63
run_timestamp: 2025-07-19_22-29-34
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
results_file_path: results/train-restricted-years/sundial/MSFT/2025-07-19_22-29-34_MSFT_1d_sundial_split_2023-01-01_train_4y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1432.7372699300545
  mae: 29.374863897873528
  rmse: 37.85151608496091
  mape: 9.705643245680994
