experiment_config_name: 2025-07-19_22-28-24_MSFT_1d_sundial_split_2023-01-01_train_1y_test_1y_horizon_21
run_timestamp: 2025-07-19_22-28-24
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
results_file_path: results/train-restricted-years/sundial/MSFT/2025-07-19_22-28-24_MSFT_1d_sundial_split_2023-01-01_train_1y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 347.19484392414125
  mae: 13.81097915290586
  rmse: 18.63316516118883
  mape: 4.367842812792714
