experiment_config_name: 2025-07-19_22-28-52_MSFT_1d_sundial_split_2023-01-01_train_6y_test_1y_horizon_21
run_timestamp: 2025-07-19_22-28-52
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
results_file_path: results/train-restricted-years/sundial/MSFT/2025-07-19_22-28-52_MSFT_1d_sundial_split_2023-01-01_train_6y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 238.71712920469022
  mae: 11.32537401597079
  rmse: 15.450473429791407
  mape: 3.7037591363995386
