experiment_config_name: 2025-07-19_22-27-23_MSFT_1d_sundial_split_2023-01-01_train_7y_test_1y_horizon_5
run_timestamp: 2025-07-19_22-27-23
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
results_file_path: results/train-restricted-years/sundial/MSFT/2025-07-19_22-27-23_MSFT_1d_sundial_split_2023-01-01_train_7y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 74.1699725255155
  mae: 6.734604089014212
  rmse: 8.612199052827071
  mape: 2.2371455375223106
