experiment_config_name: 2025-11-30_10-45-57_MSFT_1h_sundial_split_2022-03-31_train_25d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-45-57
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 25
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-market-downturn-2022-linear-pct/2025-11-30_10-45-57_MSFT_1h_sundial_split_2022-03-31_train_25d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.602591251176482e-05
  mae: 0.006060124931650544
  rmse: 0.008125633052985153
  mape: 143.0595875048055
  smape: 171.78398380538215
  mean_directional_accuracy: 46.34146341463415
