experiment_config_name: 2025-11-30_10-49-25_MSFT_1h_sundial_split_2022-03-31_train_150d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-49-25
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 150
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-market-downturn-2022-linear-pct/2025-11-30_10-49-25_MSFT_1h_sundial_split_2022-03-31_train_150d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.612823842266468e-05
  mae: 0.006039539868651937
  rmse: 0.008131927103870564
  mape: 142.61540125650504
  smape: 169.9217496504168
  mean_directional_accuracy: 45.99303135888502
