experiment_config_name: 2025-11-30_10-46-37_MSFT_1h_sundial_split_2022-03-31_train_50d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-46-37
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 50
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-market-downturn-2022-linear-pct/2025-11-30_10-46-37_MSFT_1h_sundial_split_2022-03-31_train_50d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.855713640663462e-05
  mae: 0.006173596299314466
  rmse: 0.008279923695701224
  mape: 152.53726145832297
  smape: 161.73357901608136
  mean_directional_accuracy: 52.613240418118465
