experiment_config_name: 2025-11-30_10-52-24_MSFT_1h_sundial_split_2022-03-31_train_250d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-52-24
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 250
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-market-downturn-2022-linear-pct/2025-11-30_10-52-24_MSFT_1h_sundial_split_2022-03-31_train_250d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.54800810723913e-05
  mae: 0.005980844496485324
  rmse: 0.008091976339089932
  mape: 154.9741859995873
  smape: 164.03738185408508
  mean_directional_accuracy: 50.174216027874564
