experiment_config_name: 2025-11-30_10-47-59_MSFT_1h_sundial_split_2022-03-31_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-47-59
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-market-downturn-2022-linear-pct/2025-11-30_10-47-59_MSFT_1h_sundial_split_2022-03-31_train_100d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.570098627589453e-05
  mae: 0.006087778073166792
  rmse: 0.008105614490949747
  mape: 164.15712380973233
  smape: 167.07458299255205
  mean_directional_accuracy: 47.038327526132406
