experiment_config_name: 2025-11-30_09-27-13_MSFT_1h_arima_split_2020-02-28_train_25d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-27-13
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 25
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/arima/rq3-covid-crash-2020-linear/2025-11-30_09-27-13_MSFT_1h_arima_split_2020-02-28_train_25d_test_60d_horizon_1.csv
arima_order: (0, 2, 2)
evaluation_metrics:
  mse: 7.212542493198534
  mae: 1.821934658096703
  rmse: 2.685617711663098
  mape: 1.1708906550245888
  smape: 1.1728753160352234
  mean_directional_accuracy: 100.0
