experiment_config_name: 2025-11-30_09-27-30_MSFT_1h_arima_split_2020-02-28_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-27-30
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/arima/rq3-covid-crash-2020-linear/2025-11-30_09-27-30_MSFT_1h_arima_split_2020-02-28_train_100d_test_60d_horizon_1.csv
arima_order: (1, 1, 0)
evaluation_metrics:
  mse: 7.148877089657928
  mae: 1.8093654003448527
  rmse: 2.6737384108506066
  mape: 1.1651741653936338
  smape: 1.1656847130812296
  mean_directional_accuracy: 100.0
