experiment_config_name: 2025-11-30_09-27-47_MSFT_1h_arima_split_2020-02-28_train_175d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-27-47
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 175
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/arima/rq3-covid-crash-2020-linear/2025-11-30_09-27-47_MSFT_1h_arima_split_2020-02-28_train_175d_test_60d_horizon_1.csv
arima_order: (1, 1, 0)
evaluation_metrics:
  mse: 7.151962230402484
  mae: 1.8065181753910164
  rmse: 2.6743152825354164
  mape: 1.1633581972680778
  smape: 1.1638361347311728
  mean_directional_accuracy: 100.0
