experiment_config_name: 2025-11-18_22-44-14_MSFT_1d_sundial_split_2023-01-01_train_3y_test_1y_horizon_1
run_timestamp: 2025-11-18_22-44-14
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 3.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/sundial/train-restricted-years/2025-11-18_22-44-14_MSFT_1d_sundial_split_2023-01-01_train_3y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 26.729200982669145
  mae: 3.9393967846679687
  rmse: 5.1700291084934085
  mape: 1.2795904480838272
  smape: 1.2849136756089683
  mean_directional_accuracy: 100.0
