experiment_config_name: 2025-09-15_15-58-35_MSFT_1d_sundial_split_2023-01-01_train_6y_test_1y_horizon_1
run_timestamp: 2025-09-15_15-58-35
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years/2025-09-15_15-58-35_MSFT_1d_sundial_split_2023-01-01_train_6y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 27.26243888039436
  mae: 4.107805712946364
  rmse: 5.221344547182685
  mape: 1.3580351783962041
