experiment_config_name: 2025-11-18_22-48-45_MSFT_1d_sundial_split_2023-01-01_train_6y_test_1y_horizon_1
run_timestamp: 2025-11-18_22-48-45
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years/2025-11-18_22-48-45_MSFT_1d_sundial_split_2023-01-01_train_6y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 28.344015320520473
  mae: 4.169153825683594
  rmse: 5.323909777646544
  mape: 1.360936610195868
  smape: 1.3666137877975801
  mean_directional_accuracy: 100.0
