experiment_config_name: 2025-09-28_18-55-10_MSFT_1d_sundial_split_2023-01-01_train_4y_test_1y_horizon_21
run_timestamp: 2025-09-28_18-55-10
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years/2025-09-28_18-55-10_MSFT_1d_sundial_split_2023-01-01_train_4y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 291.5734066591872
  mae: 12.654180469830287
  rmse: 17.07552068486309
  mape: 4.253172878719983
