experiment_config_name: 2025-09-28_18-57-35_MSFT_1d_sundial_split_2023-01-01_train_1y_test_1y_horizon_63
run_timestamp: 2025-09-28_18-57-35
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years/2025-09-28_18-57-35_MSFT_1d_sundial_split_2023-01-01_train_1y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1242.5544536719976
  mae: 24.952882184726615
  rmse: 35.24988586750314
  mape: 7.479620667467739
