experiment_config_name: 2025-09-28_18-57-49_MSFT_1d_sundial_split_2023-01-01_train_5y_test_1y_horizon_63
run_timestamp: 2025-09-28_18-57-49
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 5.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years/2025-09-28_18-57-49_MSFT_1d_sundial_split_2023-01-01_train_5y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1286.0817319234507
  mae: 30.116637953958982
  rmse: 35.86198170658519
  mape: 9.868589679097575
