experiment_config_name: 2025-11-17_11-55-12_MSFT_1d_sundial_split_2023-01-01_train_7y_test_1y_horizon_21
run_timestamp: 2025-11-17_11-55-12
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/sundial/train-restricted-years/2025-11-17_11-55-12_MSFT_1d_sundial_split_2023-01-01_train_7y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 200.410402513684
  mae: 10.604855561523438
  rmse: 14.156638107745922
  mape: 3.4311994904758065
  smape: 3.5242445748822875
  mean_directional_accuracy: 100.0
