experiment_config_name: 2025-09-17_17-35-30_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_1
run_timestamp: 2025-09-17_17-35-30
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years/2025-09-17_17-35-30_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 26.541478155615636
  mae: 4.0480527414221195
  rmse: 5.151842209891102
  mape: 1.3364269858889406
