experiment_config_name: 2025-11-17_11-57-50_MSFT_1d_sundial_split_2023-01-01_train_5y_test_1y_horizon_63
run_timestamp: 2025-11-17_11-57-50
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 5.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years/2025-11-17_11-57-50_MSFT_1d_sundial_split_2023-01-01_train_5y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1300.409415743811
  mae: 30.293018779296876
  rmse: 36.061189882528986
  mape: 9.707997317749943
  smape: 10.312488716318564
  mean_directional_accuracy: 100.0
