experiment_config_name: 2025-06-04_13-23-54_MSFT_1d_arima_split_2023-01-01_train_10y_test_1y_horizon_21
run_timestamp: 2025-06-04_13-23-54
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_years: 1
forecasting_method: arima
horizon_length: 21
differencing_applied: false
results_file_path: results/train-restricted-years/arima/MSFT/2025-06-04_13-23-54_MSFT_1d_arima_split_2023-01-01_train_10y_test_1y_horizon_21.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 186.30263703640307
  mae: 9.918405409413978
  rmse: 13.649272399523833
  mape: 3.181925611197479
