experiment_config_name: 2025-06-04_13-23-10_MSFT_1d_arima_split_2023-01-01_train_10y_test_1y_horizon_5
run_timestamp: 2025-06-04_13-23-10
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_years: 1
forecasting_method: arima
horizon_length: 5
differencing_applied: false
results_file_path: results/train-restricted-years/arima/MSFT/2025-06-04_13-23-10_MSFT_1d_arima_split_2023-01-01_train_10y_test_1y_horizon_5.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 62.009104169663054
  mae: 6.119589965511243
  rmse: 7.874585968142265
  mape: 2.032455398254773
