experiment_config_name: 2025-11-30_10-12-41_MSFT_1h_sundial_split_2020-02-28_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-12-41
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-linear/2025-11-30_10-12-41_MSFT_1h_sundial_split_2020-02-28_train_100d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.137355229174743
  mae: 1.806233950093233
  rmse: 2.6715829070374633
  mape: 1.165396913396285
  smape: 1.16378706039484
  mean_directional_accuracy: 100.0
