experiment_config_name: 2025-11-30_10-14-51_MSFT_1h_sundial_split_2020-02-28_train_175d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-14-51
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 175
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-linear/2025-11-30_10-14-51_MSFT_1h_sundial_split_2020-02-28_train_175d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.974516077309431
  mae: 1.8120721456813482
  rmse: 2.6409309111200603
  mape: 1.1672570091836552
  smape: 1.1667534729283229
  mean_directional_accuracy: 100.0
