experiment_config_name: 2025-11-30_10-11-59_MSFT_1h_sundial_split_2020-02-28_train_75d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-11-59
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 75
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-covid-crash-2020-linear/2025-11-30_10-11-59_MSFT_1h_sundial_split_2020-02-28_train_75d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.27500116617892
  mae: 1.81115889811765
  rmse: 2.6972210080338095
  mape: 1.1686720772929478
  smape: 1.1665757938868433
  mean_directional_accuracy: 100.0
