experiment_config_name: 2025-11-30_10-16-21_MSFT_1h_sundial_split_2020-02-28_train_225d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-16-21
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 225
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-linear/2025-11-30_10-16-21_MSFT_1h_sundial_split_2020-02-28_train_225d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.017090390390361
  mae: 1.8120938844049441
  rmse: 2.6489791223017143
  mape: 1.1676825539228182
  smape: 1.1678306664443405
  mean_directional_accuracy: 100.0
