experiment_config_name: 2025-07-25_17-12-38_MSFT_1d_chronos_base_split_2023-01-01_train_149d_test_1y_horizon_63
run_timestamp: 2025-07-25_17-12-38
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year-log/chronos_base/MSFT/2025-07-25_17-12-38_MSFT_1d_chronos_base_split_2023-01-01_train_149d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 954.1762526255352
  mae: 23.842100123177698
  rmse: 30.889743485913495
  mape: 7.2764074247074175
