experiment_config_name: 2025-07-25_17-00-38_MSFT_1d_chronos_base_split_2023-01-01_train_89d_test_1y_horizon_1
run_timestamp: 2025-07-25_17-00-38
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 89
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
results_file_path: results/train-less-year-log/chronos_base/MSFT/2025-07-25_17-00-38_MSFT_1d_chronos_base_split_2023-01-01_train_89d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 25.96864582901748
  mae: 3.895612753425371
  rmse: 5.09594405670014
  mape: 1.2894348787761574
