experiment_config_name: 2025-07-25_16-21-39_MSFT_1d_chronos_base_split_2023-01-01_train_53d_test_1y_horizon_5
run_timestamp: 2025-07-25_16-21-39
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-log/chronos_base/MSFT/2025-07-25_16-21-39_MSFT_1d_chronos_base_split_2023-01-01_train_53d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 68.44967617649483
  mae: 6.438139734859467
  rmse: 8.273431946689042
  mape: 2.133299223473104
