experiment_config_name: 2025-07-25_17-08-18_MSFT_1d_chronos_base_split_2023-01-01_train_69d_test_1y_horizon_21
run_timestamp: 2025-07-25_17-08-18
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-log/chronos_base/MSFT/2025-07-25_17-08-18_MSFT_1d_chronos_base_split_2023-01-01_train_69d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 231.7490609049857
  mae: 10.71329200196757
  rmse: 15.223306503679996
  mape: 3.4768927477449076
