experiment_config_name: 2025-07-25_17-10-40_MSFT_1d_chronos_base_split_2023-01-01_train_32d_test_1y_horizon_63
run_timestamp: 2025-07-25_17-10-40
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 32
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year-log/chronos_base/MSFT/2025-07-25_17-10-40_MSFT_1d_chronos_base_split_2023-01-01_train_32d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 670.6732269719926
  mae: 21.019441510839954
  rmse: 25.897359459450545
  mape: 6.590280068414342
