experiment_config_name: 2025-11-30_09-22-23_MSFT_1h_naive_split_2022-03-31_train_125d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-22-23
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 125
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: naive
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/naive/rq3-market-downturn-2022-linear-pct/2025-11-30_09-22-23_MSFT_1h_naive_split_2022-03-31_train_125d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0001253377923229063
  mae: 0.008507180646335983
  rmse: 0.011195436227450287
  mape: 512.5198606762283
  smape: 143.25062176263722
  mean_directional_accuracy: 54.35540069686411
