experiment_config_name: 2025-11-30_09-21-38_MSFT_1h_naive_split_2020-02-28_train_89d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-21-38
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 89
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: naive
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/naive/rq3-covid-crash-2020-log-pct/2025-11-30_09-21-38_MSFT_1h_naive_split_2020-02-28_train_89d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000825238781582949
  mae: 0.01856795405994959
  rmse: 0.02872696958579079
  mape: 401.3718800743579
  smape: 145.4463567795129
  mean_directional_accuracy: 48.08362369337979
