experiment_config_name: 2025-10-11_23-24-57_MSFT_1d_sundial_split_2023-01-01_train_250d_test_1y_horizon_21
run_timestamp: 2025-10-11_23-24-57
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 250
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-10-11_23-24-57_MSFT_1d_sundial_split_2023-01-01_train_250d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000277507418344353
  mae: 0.012429714296568122
  rmse: 0.016658553909158894
  mape: 113.90884866522815
  smape: 166.52485172335042
  mean_directional_accuracy: 44.800000000000004
