experiment_config_name: 2025-10-11_23-24-51_MSFT_1d_sundial_split_2023-01-01_train_225d_test_1y_horizon_21
run_timestamp: 2025-10-11_23-24-51
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 225
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-10-11_23-24-51_MSFT_1d_sundial_split_2023-01-01_train_225d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026535523548619423
  mae: 0.012315296087580294
  rmse: 0.016289727913203284
  mape: 130.60308733133903
  smape: 164.22714168694827
  mean_directional_accuracy: 48.4
