experiment_config_name: 2025-10-11_23-21-19_MSFT_1d_sundial_split_2023-01-01_train_175d_test_1y_horizon_5
run_timestamp: 2025-10-11_23-21-19
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-10-11_23-21-19_MSFT_1d_sundial_split_2023-01-01_train_175d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026381548427328546
  mae: 0.012262393216025156
  rmse: 0.016242397737812157
  mape: 133.51481027767213
  smape: 160.2175551363533
  mean_directional_accuracy: 51.6
