experiment_config_name: 2025-11-17_13-38-02_MSFT_1d_sundial_split_2023-01-01_train_25d_test_1y_horizon_63
run_timestamp: 2025-11-17_13-38-02
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-11-17_13-38-02_MSFT_1d_sundial_split_2023-01-01_train_25d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00027708325314217174
  mae: 0.012403406191696104
  rmse: 0.01664581788745064
  mape: 146.6511721031456
  smape: 158.78284931783406
  mean_directional_accuracy: 51.2
