experiment_config_name: 2025-11-17_13-32-43_MSFT_1d_sundial_split_2023-01-01_train_150d_test_1y_horizon_5
run_timestamp: 2025-11-17_13-32-43
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 150
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-11-17_13-32-43_MSFT_1d_sundial_split_2023-01-01_train_150d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002689992506893221
  mae: 0.012343789971523076
  rmse: 0.01640119662370164
  mape: 131.05092496282236
  smape: 164.21516555073163
  mean_directional_accuracy: 53.2
