experiment_config_name: 2025-10-11_23-08-51_MSFT_1d_sundial_split_2023-01-01_train_100d_test_1y_horizon_1
run_timestamp: 2025-10-11_23-08-51
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-10-11_23-08-51_MSFT_1d_sundial_split_2023-01-01_train_100d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026999612410588344
  mae: 0.01254132139987886
  rmse: 0.0164315587850296
  mape: 144.0599321577436
  smape: 165.1640221759894
  mean_directional_accuracy: 47.599999999999994
