experiment_config_name: 2025-11-17_13-38-58_MSFT_1d_sundial_split_2023-01-01_train_100d_test_1y_horizon_63
run_timestamp: 2025-11-17_13-38-58
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-11-17_13-38-58_MSFT_1d_sundial_split_2023-01-01_train_100d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00028051175431809914
  mae: 0.012626094553925158
  rmse: 0.016748485135023382
  mape: 124.22524923618543
  smape: 164.1611064652264
  mean_directional_accuracy: 47.599999999999994
