experiment_config_name: 2025-11-18_23-51-21_MSFT_1d_sundial_split_2023-01-01_train_125d_test_1y_horizon_1
run_timestamp: 2025-11-18_23-51-21
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-11-18_23-51-21_MSFT_1d_sundial_split_2023-01-01_train_125d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002804490157368578
  mae: 0.012472554695874076
  rmse: 0.01674661206742599
  mape: 148.41024283720435
  smape: 162.87281835163787
  mean_directional_accuracy: 53.2
