experiment_config_name: 2025-11-17_13-40-13_MSFT_1d_sundial_split_2023-01-01_train_200d_test_1y_horizon_63
run_timestamp: 2025-11-17_13-40-13
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear-pct/2025-11-17_13-40-13_MSFT_1d_sundial_split_2023-01-01_train_200d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002736333442554433
  mae: 0.012469140333534242
  rmse: 0.016541866407858676
  mape: 132.91705272499948
  smape: 164.8437712027696
  mean_directional_accuracy: 52.400000000000006
