experiment_config_name: 2025-08-31_22-14-52_MSFT_1h_chronos_base_split_2023-01-01_train_200d_test_1y_horizon_1
run_timestamp: 2025-08-31_22-14-52
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/chronos_base/train-less-year-linear/2025-08-31_22-14-52_MSFT_1h_chronos_base_split_2023-01-01_train_200d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 4.98214196436351
  mae: 1.6399920396205359
  rmse: 2.2320712274395524
  mape: 0.5268624637952928
