experiment_config_name: 2025-07-19_22-15-19_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_21
run_timestamp: 2025-07-19_22-15-19
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-log/sundial/MSFT/2025-07-19_22-15-19_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 454.18578973296354
  mae: 16.072031557912883
  rmse: 21.311635078824043
  mape: 5.132923839545418
