experiment_config_name: 2025-07-19_22-05-55_MSFT_1d_sundial_split_2023-01-01_train_53d_test_1y_horizon_1
run_timestamp: 2025-07-19_22-05-55
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: results/train-less-year-log/sundial/MSFT/2025-07-19_22-05-55_MSFT_1d_sundial_split_2023-01-01_train_53d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 29.626566698548956
  mae: 4.224209714098313
  rmse: 5.443029184061845
  mape: 1.4104615083272232
