experiment_config_name: 2025-07-19_22-12-42_MSFT_1d_sundial_split_2023-01-01_train_41d_test_1y_horizon_5
run_timestamp: 2025-07-19_22-12-42
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-log/sundial/MSFT/2025-07-19_22-12-42_MSFT_1d_sundial_split_2023-01-01_train_41d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 87.94800009269544
  mae: 7.351801755671222
  rmse: 9.378059505713079
  mape: 2.4259314218762777
