experiment_config_name: 2025-07-19_22-15-13_MSFT_1d_sundial_split_2023-01-01_train_193d_test_1y_horizon_21
run_timestamp: 2025-07-19_22-15-13
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 193
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-log/sundial/MSFT/2025-07-19_22-15-13_MSFT_1d_sundial_split_2023-01-01_train_193d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 402.30065767926936
  mae: 14.76756705529277
  rmse: 20.057433975443352
  mape: 4.726828377959199
