experiment_config_name: 2025-07-19_22-13-07_MSFT_1d_sundial_split_2023-01-01_train_69d_test_1y_horizon_5
run_timestamp: 2025-07-19_22-13-07
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-log/sundial/MSFT/2025-07-19_22-13-07_MSFT_1d_sundial_split_2023-01-01_train_69d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 95.26684785615687
  mae: 7.741831799935088
  rmse: 9.76047375162481
  mape: 2.543556445492812
