experiment_config_name: 2025-11-19_20-30-04_MSFT_1h_naive_split_2023-01-01_train_175d_test_1y_horizon_1
run_timestamp: 2025-11-19_20-30-04
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: naive
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/naive/train-less-year-linear/2025-11-19_20-30-04_MSFT_1h_naive_split_2023-01-01_train_175d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.278664114285716
  mae: 1.2276342857142857
  rmse: 1.8107081803221954
  mape: 0.3993717599868192
  smape: 0.39966791362204257
  mean_directional_accuracy: 100.0
