experiment_config_name: 2025-07-25_17-20-27_MSFT_1d_chronos_base_split_2023-01-01_train_6y_test_1y_horizon_5
run_timestamp: 2025-07-25_17-20-27
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 5
differencing_applied: false
results_file_path: results/train-restricted-years/chronos_base/MSFT/2025-07-25_17-20-27_MSFT_1d_chronos_base_split_2023-01-01_train_6y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 78.32420433392154
  mae: 7.076624533002663
  rmse: 8.850096289528242
  mape: 2.3589122439222057
