experiment_config_name: 2025-07-25_17-27-53_MSFT_1d_chronos_base_split_2023-01-01_train_8y_test_1y_horizon_63
run_timestamp: 2025-07-25_17-27-53
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: results/train-restricted-years/chronos_base/MSFT/2025-07-25_17-27-53_MSFT_1d_chronos_base_split_2023-01-01_train_8y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 717.0971415332564
  mae: 21.784741220136116
  rmse: 26.778669525076417
  mape: 7.050008015866808
