experiment_config_name: 2025-07-25_17-22-14_MSFT_1d_chronos_base_split_2023-01-01_train_1y_test_1y_horizon_21
run_timestamp: 2025-07-25_17-22-14
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
results_file_path: results/train-restricted-years/chronos_base/MSFT/2025-07-25_17-22-14_MSFT_1d_chronos_base_split_2023-01-01_train_1y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 225.86630802650475
  mae: 10.689030863257143
  rmse: 15.028849191688122
  mape: 3.4277326104162844
