experiment_config_name: 2025-07-25_17-25-36_MSFT_1d_chronos_base_split_2023-01-01_train_1y_test_1y_horizon_63
run_timestamp: 2025-07-25_17-25-36
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: results/train-restricted-years/chronos_base/MSFT/2025-07-25_17-25-36_MSFT_1d_chronos_base_split_2023-01-01_train_1y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 578.7151158230996
  mae: 18.650079369528314
  rmse: 24.056498411512422
  mape: 5.7217208994511655
