experiment_config_name: 2025-07-25_17-27-14_MSFT_1d_chronos_base_split_2023-01-01_train_6y_test_1y_horizon_63
run_timestamp: 2025-07-25_17-27-14
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: results/train-restricted-years/chronos_base/MSFT/2025-07-25_17-27-14_MSFT_1d_chronos_base_split_2023-01-01_train_6y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 694.8774189124172
  mae: 21.64272732973263
  rmse: 26.36052766756419
  mape: 7.068143566023813
