experiment_config_name: 2025-07-25_16-56-06_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_63
run_timestamp: 2025-07-25_16-56-06
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year-linear/chronos_base/MSFT/2025-07-25_16-56-06_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1138.6153659020063
  mae: 26.41601696399716
  rmse: 33.74337514093702
  mape: 8.189849575769266
