experiment_config_name: 2025-07-23_21-31-02_MSFT_1d_chronos_base_split_2023-01-01_train_75d_test_1y_horizon_63
run_timestamp: 2025-07-23_21-31-02
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 75
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year-linear/chronos_base/MSFT/2025-07-23_21-31-02_MSFT_1d_chronos_base_split_2023-01-01_train_75d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 533.1751146338328
  mae: 18.440397843792454
  rmse: 23.09058497816443
  mape: 5.7403464723046405
