experiment_config_name: 2025-07-25_16-52-24_MSFT_1d_chronos_base_split_2023-01-01_train_100d_test_1y_horizon_21
run_timestamp: 2025-07-25_16-52-24
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-linear/chronos_base/MSFT/2025-07-25_16-52-24_MSFT_1d_chronos_base_split_2023-01-01_train_100d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 227.690677525256
  mae: 10.995559910723685
  rmse: 15.089422703511755
  mape: 3.543083973650797
