experiment_config_name: 2025-07-23_21-29-40_MSFT_1d_chronos_base_split_2023-01-01_train_175d_test_1y_horizon_21
run_timestamp: 2025-07-23_21-29-40
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-linear/chronos_base/MSFT/2025-07-23_21-29-40_MSFT_1d_chronos_base_split_2023-01-01_train_175d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 196.73870451116744
  mae: 10.679152478621424
  rmse: 14.02635749263391
  mape: 3.4717812762620044
