experiment_config_name: 2025-06-04_14-56-32_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_63
run_timestamp: 2025-06-04_14-56-32
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year-log/fm/MSFT/2025-06-04_14-56-32_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 601.8594272826418
  mae: 18.34112248548867
  rmse: 24.532823467400604
  mape: 6.2818608145605985
