experiment_config_name: 2025-06-04_14-26-38_MSFT_1d_fm_split_2023-01-01_train_89d_test_1y_horizon_1
run_timestamp: 2025-06-04_14-26-38
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 89
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: results/train-less-year-log/fm/MSFT/2025-06-04_14-26-38_MSFT_1d_fm_split_2023-01-01_train_89d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 1.5048988244246648
  mae: 0.9630875088472038
  rmse: 1.2267431778594349
  mape: 0.31615257775877137
