experiment_config_name: 2025-05-08_16-11-08_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_5
run_timestamp: 2025-05-08_16-11-08
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-log/fm/MSFT/2025-05-08_16-11-08_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 30.44267182319279
  mae: 4.064774169832176
  rmse: 5.517487818128173
  mape: 1.3415893007578474
