experiment_config_name: 2025-06-04_14-47-46_MSFT_1d_fm_split_2023-01-01_train_116d_test_1y_horizon_5
run_timestamp: 2025-06-04_14-47-46
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-log/fm/MSFT/2025-06-04_14-47-46_MSFT_1d_fm_split_2023-01-01_train_116d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 32.76765090365179
  mae: 4.252362996961427
  rmse: 5.724303530007104
  mape: 1.414278962653116
