experiment_config_name: 2025-05-08_16-15-30_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_21
run_timestamp: 2025-05-08_16-15-30
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-log/fm/MSFT/2025-05-08_16-15-30_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 195.11516319218055
  mae: 11.158687004792588
  rmse: 13.968362938876572
  mape: 3.713658332167917
