experiment_config_name: 2025-10-12_17-23-49_MSFT_1h_fm_split_2023-01-01_train_8y_test_1y_horizon_1
run_timestamp: 2025-10-12_17-23-49
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/train-restricted-years-pct/2025-10-12_17-23-49_MSFT_1h_fm_split_2023-01-01_train_8y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.6403934586010466e-05
  mae: 0.004035040047525228
  rmse: 0.006033567318428665
  mape: 466090466743.78864
  smape: 173.44712612465463
  mean_directional_accuracy: 48.68571428571429
