experiment_config_name: 2025-09-15_16-47-04_MSFT_1d_chronos_base_split_2023-01-01_train_32d_test_1y_horizon_1
run_timestamp: 2025-09-15_16-47-04
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 32
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-log/2025-09-15_16-47-04_MSFT_1d_chronos_base_split_2023-01-01_train_32d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 25.746856112115957
  mae: 3.877499136711657
  rmse: 5.074135996612227
  mape: 1.2852541304471983
