experiment_config_name: 2025-11-30_19-16-17_MSFT_1h_fm_split_2020-02-28_train_125d_test_60d_horizon_1
run_timestamp: 2025-11-30_19-16-17
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 125
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/rq3-covid-crash-2020-linear-pct/2025-11-30_19-16-17_MSFT_1h_fm_split_2020-02-28_train_125d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003355192177391423
  mae: 0.012073625128254072
  rmse: 0.01831718367378409
  mape: 135.71486884301493
  smape: 168.56871739430093
  mean_directional_accuracy: 48.78048780487805
