experiment_config_name: 2025-10-11_23-22-51_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_21
run_timestamp: 2025-10-11_23-22-51
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-10-11_23-22-51_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026086430433761585
  mae: 0.012190664615587281
  rmse: 0.016151294200082416
  mape: 119.61302366996442
  smape: 169.79908674089575
  mean_directional_accuracy: 52.400000000000006
