experiment_config_name: 2025-10-11_22-54-55_MSFT_1d_sundial_split_2023-01-01_train_9y_test_1y_horizon_1
run_timestamp: 2025-10-11_22-54-55
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 9.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-10-11_22-54-55_MSFT_1d_sundial_split_2023-01-01_train_9y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002634123439838256
  mae: 0.012174727169131582
  rmse: 0.0162299828707188
  mape: 117.78607413433582
  smape: 164.4915838480194
  mean_directional_accuracy: 56.8
