experiment_config_name: 2025-11-17_12-55-59_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_5
run_timestamp: 2025-11-17_12-55-59
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-11-17_12-55-59_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002765069069873517
  mae: 0.012359843900583778
  rmse: 0.01662849683487211
  mape: 114.97665330560677
  smape: 168.89646633630304
  mean_directional_accuracy: 50.8
