experiment_config_name: 2025-10-11_23-15-39_MSFT_1d_sundial_split_2023-01-01_train_2y_test_1y_horizon_5
run_timestamp: 2025-10-11_23-15-39
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-10-11_23-15-39_MSFT_1d_sundial_split_2023-01-01_train_2y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002638482038344888
  mae: 0.012181687290569279
  rmse: 0.016243404933525753
  mape: 107.4942915844471
  smape: 163.84004639840504
  mean_directional_accuracy: 50.0
