experiment_config_name: 2025-10-11_23-25-29_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_63
run_timestamp: 2025-10-11_23-25-29
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-10-11_23-25-29_MSFT_1d_sundial_split_2023-01-01_train_8y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00025788704228171014
  mae: 0.012102544175400555
  rmse: 0.016058861799072503
  mape: 110.96924329740077
  smape: 164.23345357550633
  mean_directional_accuracy: 53.6
