experiment_config_name: 2025-10-11_22-55-59_MSFT_1d_sundial_split_2023-01-01_train_10y_test_1y_horizon_1
run_timestamp: 2025-10-11_22-55-59
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-10-11_22-55-59_MSFT_1d_sundial_split_2023-01-01_train_10y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026398494984249354
  mae: 0.012266809998497248
  rmse: 0.016247613666089355
  mape: 120.3065199300756
  smape: 162.75479560665903
  mean_directional_accuracy: 52.800000000000004
