experiment_config_name: 2025-11-17_12-57-59_MSFT_1d_sundial_split_2023-01-01_train_3y_test_1y_horizon_21
run_timestamp: 2025-11-17_12-57-59
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 3.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/sundial/train-restricted-years-pct/2025-11-17_12-57-59_MSFT_1d_sundial_split_2023-01-01_train_3y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002685429295948132
  mae: 0.01214103918101402
  rmse: 0.016387279505604743
  mape: 119.63979933313007
  smape: 163.28424145906243
  mean_directional_accuracy: 53.6
