experiment_config_name: 2025-10-11_22-50-01_MSFT_1d_sundial_split_2023-01-01_train_4y_test_1y_horizon_1
run_timestamp: 2025-10-11_22-50-01
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-10-11_22-50-01_MSFT_1d_sundial_split_2023-01-01_train_4y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00025930383832785674
  mae: 0.012068747144330068
  rmse: 0.016102913970081834
  mape: 114.09480009851708
  smape: 157.44488766017056
  mean_directional_accuracy: 57.199999999999996
