experiment_config_name: 2025-11-17_12-57-19_MSFT_1d_sundial_split_2023-01-01_train_1y_test_1y_horizon_21
run_timestamp: 2025-11-17_12-57-19
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-restricted-years-pct/2025-11-17_12-57-19_MSFT_1d_sundial_split_2023-01-01_train_1y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002921247004423586
  mae: 0.012655473810069283
  rmse: 0.017091655871867964
  mape: 136.36659931265655
  smape: 166.41880302269914
  mean_directional_accuracy: 44.800000000000004
