experiment_config_name: 2025-11-30_09-19-26_MSFT_1h_naive_split_2020-02-28_train_249d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-19-26
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 249
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: naive
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/naive/rq3-covid-crash-2020-log/2025-11-30_09-19-26_MSFT_1h_naive_split_2020-02-28_train_249d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.588671428571435
  mae: 1.8352961672473875
  rmse: 2.7547543318001035
  mape: 1.1821188588681217
  smape: 1.181987565957524
  mean_directional_accuracy: 100.0
