experiment_config_name: 2025-11-30_11-15-36_MSFT_1h_chronos_base_split_2020-02-28_train_175d_test_60d_horizon_1
run_timestamp: 2025-11-30_11-15-36
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 175
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/chronos_base/rq3-covid-crash-2020-linear/2025-11-30_11-15-36_MSFT_1h_chronos_base_split_2020-02-28_train_175d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.8629562733511476
  mae: 1.9638988534747932
  rmse: 2.804096338100948
  mape: 1.262816568732888
  smape: 1.2673376780884376
  mean_directional_accuracy: 100.0
