experiment_config_name: 2025-10-11_23-05-18_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_1
run_timestamp: 2025-10-11_23-05-18
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log-pct/2025-10-11_23-05-18_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00025897530217735556
  mae: 0.012221693021428458
  rmse: 0.01609270959712365
  mape: 120.58526940803549
  smape: 166.5392329838993
  mean_directional_accuracy: 50.0
