experiment_config_name: 2025-11-18_23-38-15_MSFT_1d_sundial_split_2023-01-01_train_25d_test_1y_horizon_1
run_timestamp: 2025-11-18_23-38-15
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log-pct/2025-11-18_23-38-15_MSFT_1d_sundial_split_2023-01-01_train_25d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002909179144678533
  mae: 0.01265851091584001
  rmse: 0.017056315969981715
  mape: 147.06179176296465
  smape: 158.88787965506697
  mean_directional_accuracy: 51.6
