experiment_config_name: 2025-11-18_23-40-55_MSFT_1d_sundial_split_2023-01-01_train_41d_test_1y_horizon_1
run_timestamp: 2025-11-18_23-40-55
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/sundial/train-less-year-log-pct/2025-11-18_23-40-55_MSFT_1d_sundial_split_2023-01-01_train_41d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003043927161423429
  mae: 0.013117323266821914
  rmse: 0.017446854047143943
  mape: 150.7901295126528
  smape: 160.52755524964212
  mean_directional_accuracy: 49.2
