experiment_config_name: 2025-10-11_23-19-05_MSFT_1d_sundial_split_2023-01-01_train_116d_test_1y_horizon_5
run_timestamp: 2025-10-11_23-19-05
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log-pct/2025-10-11_23-19-05_MSFT_1d_sundial_split_2023-01-01_train_116d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002710598427963718
  mae: 0.012366877129754933
  rmse: 0.016463895128321603
  mape: 131.44698702265828
  smape: 163.28898181824235
  mean_directional_accuracy: 51.2
