experiment_config_name: 2025-11-17_13-14-53_MSFT_1d_sundial_split_2023-01-01_train_149d_test_1y_horizon_5
run_timestamp: 2025-11-17_13-14-53
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log-pct/2025-11-17_13-14-53_MSFT_1d_sundial_split_2023-01-01_train_149d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002750271637302368
  mae: 0.01243445618789418
  rmse: 0.016583942948835684
  mape: 137.28014069583077
  smape: 163.8423227988355
  mean_directional_accuracy: 50.0
