experiment_config_name: 2025-11-17_13-14-05_MSFT_1d_sundial_split_2023-01-01_train_89d_test_1y_horizon_5
run_timestamp: 2025-11-17_13-14-05
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 89
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log-pct/2025-11-17_13-14-05_MSFT_1d_sundial_split_2023-01-01_train_89d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00028737854264731426
  mae: 0.012763619698791766
  rmse: 0.016952242997530276
  mape: 147.17173796293915
  smape: 165.07526612125326
  mean_directional_accuracy: 46.800000000000004
