experiment_config_name: 2025-11-30_17-02-05_MSFT_1h_fm_split_2022-03-31_train_41d_test_60d_horizon_1
run_timestamp: 2025-11-30_17-02-05
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 41
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/rq3-market-downturn-2022-log/2025-11-30_17-02-05_MSFT_1h_fm_split_2022-03-31_train_41d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 5.784324630178708
  mae: 1.810756168166103
  rmse: 2.405062292369723
  mape: 0.6535748353356114
  smape: 0.6534925538202034
  mean_directional_accuracy: 100.0
