experiment_config_name: 2025-06-04_13-01-11_MSFT_1d_naive_split_2023-01-01_train_9y_test_1y_horizon_1
run_timestamp: 2025-06-04_13-01-11
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 9.0
training_period_unit: years
test_period_years: 1
forecasting_method: naive
horizon_length: 1
differencing_applied: false
results_file_path: results/train-restricted-years/naive/MSFT/2025-06-04_13-01-11_MSFT_1d_naive_split_2023-01-01_train_9y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 23.05671797311985
  mae: 3.6720842285649433
  rmse: 4.801741139745024
  mape: 1.2183760536503425
