experiment_config_name: 2025-11-17_16-07-08_MSFT_1d_fm_split_2023-01-01_train_7y_test_1y_horizon_5
run_timestamp: 2025-11-17_16-07-08
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-restricted-years/2025-11-17_16-07-08_MSFT_1d_fm_split_2023-01-01_train_7y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 63.083248650473124
  mae: 6.172813703613281
  rmse: 7.942496373966634
  mape: 2.0075959452756758
  smape: 2.013319525650086
  mean_directional_accuracy: 100.0
