experiment_config_name: 2025-11-17_16-09-44_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_21
run_timestamp: 2025-11-17_16-09-44
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-11-17_16-09-44_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 195.32354568776566
  mae: 10.181735007324217
  rmse: 13.9758200363258
  mape: 3.235905469772386
  smape: 3.3117692274752684
  mean_directional_accuracy: 100.0
