experiment_config_name: 2025-11-17_16-05-11_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_5
run_timestamp: 2025-11-17_16-05-11
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-11-17_16-05-11_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 62.50992857462564
  mae: 6.205010209960935
  rmse: 7.906322063679523
  mape: 2.0350908282881846
  smape: 2.0372233147559666
  mean_directional_accuracy: 100.0
