experiment_config_name: 2025-11-17_15-50-43_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_1
run_timestamp: 2025-11-17_15-50-43
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-11-17_15-50-43_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 29.82431015379664
  mae: 4.270870302734377
  rmse: 5.461163809463752
  mape: 1.3859422286662404
  smape: 1.3936792978701262
  mean_directional_accuracy: 100.0
