experiment_config_name: 2025-11-17_16-11-02_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_21
run_timestamp: 2025-11-17_16-11-02
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-restricted-years/2025-11-17_16-11-02_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 179.90898850736914
  mae: 9.642780368652344
  rmse: 13.413015638079646
  mape: 3.083728673346204
  smape: 3.1508210070168334
  mean_directional_accuracy: 100.0
