experiment_config_name: 2025-09-28_19-03-05_MSFT_1d_fm_split_2023-01-01_train_9y_test_1y_horizon_1
run_timestamp: 2025-09-28_19-03-05
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 9.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-09-28_19-03-05_MSFT_1d_fm_split_2023-01-01_train_9y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 27.57462179331177
  mae: 4.103648040407486
  rmse: 5.251154329603327
  mape: 1.349972074537077
