experiment_config_name: 2025-09-28_18-42-13_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_1
run_timestamp: 2025-09-28_18-42-13
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-09-28_18-42-13_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 24.02304689469555
  mae: 3.795886505413909
  rmse: 4.901331134977063
  mape: 1.2600709098658147
