experiment_config_name: 2025-09-28_19-58-16_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_5
run_timestamp: 2025-09-28_19-58-16
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-09-28_19-58-16_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 65.96297550806777
  mae: 6.261336365693721
  rmse: 8.121759385014295
  mape: 2.084496268665396
