experiment_config_name: 2025-11-17_15-57-51_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_1
run_timestamp: 2025-11-17_15-57-51
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-11-17_15-57-51_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 28.646831669059743
  mae: 4.072548588867188
  rmse: 5.352273504694967
  mape: 1.3271047805474336
  smape: 1.3275090373276555
  mean_directional_accuracy: 100.0
