experiment_config_name: 2025-09-28_20-22-50_MSFT_1d_fm_split_2023-01-01_train_5y_test_1y_horizon_63
run_timestamp: 2025-09-28_20-22-50
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 5.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-09-28_20-22-50_MSFT_1d_fm_split_2023-01-01_train_5y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 840.8585938820837
  mae: 23.245249600041127
  rmse: 28.997561860992448
  mape: 7.310455975705074
