experiment_config_name: 2025-09-28_20-17-43_MSFT_1d_fm_split_2023-01-01_train_10y_test_1y_horizon_21
run_timestamp: 2025-09-28_20-17-43
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-09-28_20-17-43_MSFT_1d_fm_split_2023-01-01_train_10y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 187.19536519003765
  mae: 10.05216518820136
  rmse: 13.681935725256045
  mape: 3.248475773701043
