experiment_config_name: 2025-11-17_16-14-06_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_63
run_timestamp: 2025-11-17_16-14-06
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-11-17_16-14-06_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1004.9187315838645
  mae: 24.14463764404297
  rmse: 31.70045317631697
  mape: 7.366160138661041
  smape: 7.810146067325984
  mean_directional_accuracy: 100.0
