experiment_config_name: 2025-11-17_15-47-09_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_1
run_timestamp: 2025-11-17_15-47-09
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-11-17_15-47-09_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 25.702814857335795
  mae: 3.8587797900390615
  rmse: 5.0697943604584
  mape: 1.2594400058860515
  smape: 1.2593177642597775
  mean_directional_accuracy: 100.0
