experiment_config_name: 2025-09-15_12-39-06_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_1
run_timestamp: 2025-09-15_12-39-06
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-09-15_12-39-06_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 28.62896723638956
  mae: 4.188540509183434
  rmse: 5.350604380477925
  mape: 1.3868715951713508
