experiment_config_name: 2025-11-17_16-03-53_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_5
run_timestamp: 2025-11-17_16-03-53
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years/2025-11-17_16-03-53_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 64.11975532642381
  mae: 6.130269506835937
  rmse: 8.007481209870168
  mape: 1.997200611488961
  smape: 2.010183684684266
  mean_directional_accuracy: 100.0
