experiment_config_name: 2025-11-16_23-02-35_MSFT_1d_naive_split_2023-01-01_train_149d_test_1y_horizon_5
run_timestamp: 2025-11-16_23-02-35
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: naive
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/naive/train-less-year-log/2025-11-16_23-02-35_MSFT_1d_naive_split_2023-01-01_train_149d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 61.33029639999997
  mae: 6.032760000000001
  rmse: 7.8313661898802795
  mape: 1.9747521661705747
  smape: 1.9821629538512886
  mean_directional_accuracy: 100.0
