experiment_config_name: 2025-11-17_17-18-46_MSFT_1d_fm_split_2023-01-01_train_250d_test_1y_horizon_21
run_timestamp: 2025-11-17_17-18-46
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 250
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-linear/2025-11-17_17-18-46_MSFT_1d_fm_split_2023-01-01_train_250d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 233.37201929941727
  mae: 11.37983429199219
  rmse: 15.276518559521907
  mape: 3.6600431183280704
  smape: 3.754954692941894
  mean_directional_accuracy: 100.0
