experiment_config_name: 2025-11-17_17-03-01_MSFT_1d_fm_split_2023-01-01_train_200d_test_1y_horizon_1
run_timestamp: 2025-11-17_17-03-01
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear/2025-11-17_17-03-01_MSFT_1d_fm_split_2023-01-01_train_200d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 26.6938679647645
  mae: 3.99628271484375
  rmse: 5.166610878009346
  mape: 1.3076027389248936
  smape: 1.3128776318111621
  mean_directional_accuracy: 100.0
