experiment_config_name: 2025-09-28_20-20-44_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_21
run_timestamp: 2025-09-28_20-20-44
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear/2025-09-28_20-20-44_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 391.8164646981574
  mae: 14.565677954324856
  rmse: 19.79435436426653
  mape: 4.748140190097072
