experiment_config_name: 2025-11-17_17-14-11_MSFT_1d_fm_split_2023-01-01_train_250d_test_1y_horizon_5
run_timestamp: 2025-11-17_17-14-11
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 250
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-linear/2025-11-17_17-14-11_MSFT_1d_fm_split_2023-01-01_train_250d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 62.79931021960305
  mae: 6.1552138427734375
  rmse: 7.924601581127158
  mape: 2.0184214147352124
  smape: 2.030055384036363
  mean_directional_accuracy: 100.0
