experiment_config_name: 2025-11-17_17-08-20_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_5
run_timestamp: 2025-11-17_17-08-20
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear/2025-11-17_17-08-20_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 63.209259261425686
  mae: 6.221821352539062
  rmse: 7.950425099416112
  mape: 2.040483490752867
  smape: 2.055793739194877
  mean_directional_accuracy: 100.0
