experiment_config_name: 2025-09-28_20-13-25_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_5
run_timestamp: 2025-09-28_20-13-25
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear/2025-09-28_20-13-25_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 67.5308959470787
  mae: 6.421635995202975
  rmse: 8.217718414929944
  mape: 2.1383950249573616
