experiment_config_name: 2025-09-28_19-50-45_MSFT_1d_fm_split_2023-01-01_train_200d_test_1y_horizon_1
run_timestamp: 2025-09-28_19-50-45
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear/2025-09-28_19-50-45_MSFT_1d_fm_split_2023-01-01_train_200d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 25.342080102769035
  mae: 3.9250069447168077
  rmse: 5.034091785294447
  mape: 1.301397671516912
