experiment_config_name: 2025-09-28_19-43-14_MSFT_1d_fm_split_2023-01-01_train_125d_test_1y_horizon_1
run_timestamp: 2025-09-28_19-43-14
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear/2025-09-28_19-43-14_MSFT_1d_fm_split_2023-01-01_train_125d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 24.006628434727013
  mae: 3.783287637426728
  rmse: 4.899655950648679
  mape: 1.2551920552551765
