experiment_config_name: 2025-09-28_20-21-23_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_21
run_timestamp: 2025-09-28_20-21-23
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear/2025-09-28_20-21-23_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 287.48271256160444
  mae: 12.577321708509013
  rmse: 16.955315171402873
  mape: 4.085281843065376
