experiment_config_name: 2025-11-30_09-23-41_MSFT_1h_arima_split_2008-01-20_train_193d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-23-41
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 193
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/arima/rq3-financial-crisis-2008-log/2025-11-30_09-23-41_MSFT_1h_arima_split_2008-01-20_train_193d_test_60d_horizon_1.csv
arima_order: (1, 1, 0)
evaluation_metrics:
  mse: 0.07870955664118473
  mae: 0.1736881056015493
  rmse: 0.2805522351384582
  mape: 0.5859166791949697
  smape: 0.5854019148580047
  mean_directional_accuracy: 100.0
