experiment_config_name: 2025-10-11_23-58-44_MSFT_1d_chronos_base_split_2023-01-01_train_5y_test_1y_horizon_63
run_timestamp: 2025-10-11_23-58-44
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 5.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-restricted-years-pct/2025-10-11_23-58-44_MSFT_1d_chronos_base_split_2023-01-01_train_5y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026064275653933303
  mae: 0.012214330780104234
  rmse: 0.01614443422791065
  mape: 105.56762547631303
  smape: 174.13142654166492
  mean_directional_accuracy: 53.2
