experiment_config_name: 2025-11-18_22-22-28_MSFT_1d_chronos_base_split_2023-01-01_train_10y_test_1y_horizon_1
run_timestamp: 2025-11-18_22-22-28
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/chronos_base/train-restricted-years-pct/2025-11-18_22-22-28_MSFT_1d_chronos_base_split_2023-01-01_train_10y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000276307503518121
  mae: 0.012334677398888862
  rmse: 0.01662249991782587
  mape: 100.9206941660585
  smape: 183.99350977815394
  mean_directional_accuracy: 50.4
