experiment_config_name: 2025-10-11_23-44-36_MSFT_1d_chronos_base_split_2023-01-01_train_1y_test_1y_horizon_1
run_timestamp: 2025-10-11_23-44-36
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-restricted-years-pct/2025-10-11_23-44-36_MSFT_1d_chronos_base_split_2023-01-01_train_1y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002655103290360931
  mae: 0.012309933288752007
  rmse: 0.016294487688666162
  mape: 106.02791391580548
  smape: 180.36876698272047
  mean_directional_accuracy: 50.8
