experiment_config_name: 2025-09-28_18-51-08_MSFT_1d_sundial_split_2023-01-01_train_53d_test_1y_horizon_5
run_timestamp: 2025-09-28_18-51-08
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log/2025-09-28_18-51-08_MSFT_1d_sundial_split_2023-01-01_train_53d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 89.41303686553805
  mae: 7.411743085807581
  rmse: 9.455846702730435
  mape: 2.447491076749837
