experiment_config_name: 2025-11-17_12-15-38_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_21
run_timestamp: 2025-11-17_12-15-38
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/sundial/train-less-year-log/2025-11-17_12-15-38_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 441.0672627965499
  mae: 15.72782921875
  rmse: 21.001601434094255
  mape: 4.996874958450164
  smape: 5.213054429966733
  mean_directional_accuracy: 100.0
