experiment_config_name: 2025-09-28_18-58-43_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_63
run_timestamp: 2025-09-28_18-58-43
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log/2025-09-28_18-58-43_MSFT_1d_sundial_split_2023-01-01_train_249d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1861.9205067831033
  mae: 32.30548892529057
  rmse: 43.1499769036219
  mape: 9.86957062266913
