experiment_config_name: 2025-09-15_16-09-59_MSFT_1d_sundial_split_2023-01-01_train_69d_test_1y_horizon_1
run_timestamp: 2025-09-15_16-09-59
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log/2025-09-15_16-09-59_MSFT_1d_sundial_split_2023-01-01_train_69d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 28.358552742392206
  mae: 4.109015387933181
  rmse: 5.325274898293252
  mape: 1.3588644087115143
