experiment_config_name: 2025-09-28_18-50-55_MSFT_1d_sundial_split_2023-01-01_train_41d_test_1y_horizon_5
run_timestamp: 2025-09-28_18-50-55
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log/2025-09-28_18-50-55_MSFT_1d_sundial_split_2023-01-01_train_41d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 87.74904272308171
  mae: 7.368083463043533
  rmse: 9.367445901796376
  mape: 2.435809985367224
