experiment_config_name: 2025-09-15_16-06-31_MSFT_1d_sundial_split_2023-01-01_train_32d_test_1y_horizon_1
run_timestamp: 2025-09-15_16-06-31
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 32
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-log/2025-09-15_16-06-31_MSFT_1d_sundial_split_2023-01-01_train_32d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 28.184186471237634
  mae: 4.074435257170747
  rmse: 5.30887808027625
  mape: 1.3526913170707797
