experiment_config_name: 2025-06-04_14-54-14_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_21
run_timestamp: 2025-06-04_14-54-14
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-linear/fm/MSFT/2025-06-04_14-54-14_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 245.79365998780204
  mae: 12.186413425168626
  rmse: 15.67780788209251
  mape: 4.067610295960239
