experiment_config_name: 2025-06-08_23-55-05_MSFT_1d_fm_split_2023-01-01_train_125d_test_1y_horizon_5
run_timestamp: 2025-06-08_23-55-05
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-linear/fm/MSFT/2025-06-08_23-55-05_MSFT_1d_fm_split_2023-01-01_train_125d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 66.71902393233904
  mae: 6.3513702474646685
  rmse: 8.168171394647583
  mape: 2.1106119042602725
