experiment_config_name: 2025-06-04_14-31-44_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_1
run_timestamp: 2025-06-04_14-31-44
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 150
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: results/train-less-year-linear/fm/MSFT/2025-06-04_14-31-44_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 1.5657577907767455
  mae: 0.9950151743092314
  rmse: 1.251302437773037
  mape: 0.32658807919889904
