experiment_config_name: 2025-06-04_14-47-48_MSFT_1d_fm_split_2023-01-01_train_50d_test_1y_horizon_5
run_timestamp: 2025-06-04_14-47-48
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 50
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-linear/fm/MSFT/2025-06-04_14-47-48_MSFT_1d_fm_split_2023-01-01_train_50d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 31.333499395462205
  mae: 4.078738904350247
  rmse: 5.597633374513037
  mape: 1.3441305477815941
