experiment_config_name: 2025-06-04_14-53-35_MSFT_1d_fm_split_2023-01-01_train_250d_test_1y_horizon_5
run_timestamp: 2025-06-04_14-53-35
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 250
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-linear/fm/MSFT/2025-06-04_14-53-35_MSFT_1d_fm_split_2023-01-01_train_250d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 34.62190828545373
  mae: 4.455102263783311
  rmse: 5.8840384333766655
  mape: 1.478883101304323
