experiment_config_name: 2025-05-08_17-29-12_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_63
run_timestamp: 2025-05-08_17-29-12
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year/arima/MSFT/2025-05-08_17-29-12_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_63.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 3408.015616679484
  mae: 51.09751961377358
  rmse: 58.378211831808315
  mape: 15.662123184680793
