experiment_config_name: 2025-11-30_10-42-14_MSFT_1h_sundial_split_2008-01-20_train_150d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-42-14
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 150
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-financial-crisis-2008-linear-pct/2025-11-30_10-42-14_MSFT_1h_sundial_split_2008-01-20_train_150d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 8.552478728485672e-05
  mae: 0.005935905548382764
  rmse: 0.0092479612501814
  mape: 2134389041526.8967
  smape: 165.0717871278677
  mean_directional_accuracy: 44.94773519163763
