experiment_config_name: 2025-11-30_10-40-49_MSFT_1h_sundial_split_2008-01-20_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-40-49
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-financial-crisis-2008-linear-pct/2025-11-30_10-40-49_MSFT_1h_sundial_split_2008-01-20_train_100d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 8.556576132930373e-05
  mae: 0.005994348387462247
  rmse: 0.00925017628639064
  mape: 4662132995861.066
  smape: 166.10239400235082
  mean_directional_accuracy: 49.12891986062718
