experiment_config_name: 2025-11-30_11-30-03_MSFT_1h_chronos_base_split_2022-03-31_train_250d_test_60d_horizon_1
run_timestamp: 2025-11-30_11-30-03
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 250
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/chronos_base/rq3-market-downturn-2022-linear-pct/2025-11-30_11-30-03_MSFT_1h_chronos_base_split_2022-03-31_train_250d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.367587440621373e-05
  mae: 0.005890073849391295
  rmse: 0.007979716436453975
  mape: 111.00867092430462
  smape: 178.57185239252226
  mean_directional_accuracy: 50.174216027874564
