experiment_config_name: 2025-09-28_18-59-16_MSFT_1d_sundial_split_2023-01-01_train_225d_test_1y_horizon_63
run_timestamp: 2025-09-28_18-59-16
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 225
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear/2025-09-28_18-59-16_MSFT_1d_sundial_split_2023-01-01_train_225d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1839.1309111657738
  mae: 31.82639079669378
  rmse: 42.885089613591504
  mape: 9.737058519015717
