experiment_config_name: 2025-11-17_12-23-25_MSFT_1d_sundial_split_2023-01-01_train_150d_test_1y_horizon_1
run_timestamp: 2025-11-17_12-23-25
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 150
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear/2025-11-17_12-23-25_MSFT_1d_sundial_split_2023-01-01_train_150d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 27.223274747138245
  mae: 3.9949301293945316
  rmse: 5.217592811550001
  mape: 1.296083047712713
  smape: 1.3016102157369385
  mean_directional_accuracy: 100.0
