experiment_config_name: 2025-11-17_12-34-57_MSFT_1d_sundial_split_2023-01-01_train_250d_test_1y_horizon_21
run_timestamp: 2025-11-17_12-34-57
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 250
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear/2025-11-17_12-34-57_MSFT_1d_sundial_split_2023-01-01_train_250d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 403.061582607371
  mae: 14.955105349121093
  rmse: 20.076393665381513
  mape: 4.726641310977383
  smape: 4.917748817953155
  mean_directional_accuracy: 100.0
