experiment_config_name: 2025-09-17_17-55-53_MSFT_1d_sundial_split_2023-01-01_train_100d_test_1y_horizon_1
run_timestamp: 2025-09-17_17-55-53
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/sundial/train-less-year-linear/2025-09-17_17-55-53_MSFT_1d_sundial_split_2023-01-01_train_100d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 29.475076149525773
  mae: 4.253992410192765
  rmse: 5.429095334355971
  mape: 1.4105938803874851
