experiment_config_name: 2025-11-17_12-31-54_MSFT_1d_sundial_split_2023-01-01_train_25d_test_1y_horizon_21
run_timestamp: 2025-11-17_12-31-54
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/sundial/train-less-year-linear/2025-11-17_12-31-54_MSFT_1d_sundial_split_2023-01-01_train_25d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 406.07089618257083
  mae: 15.420533020019532
  rmse: 20.151200862047176
  mape: 5.003819394824397
  smape: 5.201379350182326
  mean_directional_accuracy: 100.0
