experiment_config_name: 2025-11-17_16-39-43_MSFT_1d_fm_split_2023-01-01_train_116d_test_1y_horizon_5
run_timestamp: 2025-11-17_16-39-43
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-log/2025-11-17_16-39-43_MSFT_1d_fm_split_2023-01-01_train_116d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 64.47643415145086
  mae: 6.175504926757812
  rmse: 8.029721922423644
  mape: 2.0236172430505825
  smape: 2.035565152088361
  mean_directional_accuracy: 100.0
