experiment_config_name: 2025-09-28_20-04-10_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_5
run_timestamp: 2025-09-28_20-04-10
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-09-28_20-04-10_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 62.51275618763895
  mae: 6.193316368951907
  rmse: 7.906500881403793
  mape: 2.0570084862785096
