experiment_config_name: 2025-11-20_06-55-28_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_1
run_timestamp: 2025-11-20_06-55-28
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 193
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-11-20_06-55-28_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 26.303363297041138
  mae: 3.9906571118164056
  rmse: 5.128680463534566
  mape: 1.3087922085067993
  smape: 1.3147520536352013
  mean_directional_accuracy: 100.0
