experiment_config_name: 2025-11-17_16-48-15_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_63
run_timestamp: 2025-11-17_16-48-15
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-log/2025-11-17_16-48-15_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1175.6821107777282
  mae: 26.102035937500006
  rmse: 34.28822116671741
  mape: 7.984435461875003
  smape: 8.513322023431762
  mean_directional_accuracy: 100.0
