experiment_config_name: 2025-11-17_16-23-23_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_1
run_timestamp: 2025-11-17_16-23-23
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-log/2025-11-17_16-23-23_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 26.184308449478674
  mae: 3.952137756347656
  rmse: 5.117060528221127
  mape: 1.2985443747803298
  smape: 1.3032903067405355
  mean_directional_accuracy: 100.0
