experiment_config_name: 2025-11-17_16-49-26_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_63
run_timestamp: 2025-11-17_16-49-26
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-11-17_16-49-26_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1261.0187068311088
  mae: 26.76336857666016
  rmse: 35.51082520628194
  mape: 8.190352680924514
  smape: 8.783439639515844
  mean_directional_accuracy: 100.0
