experiment_config_name: 2025-09-28_20-18-22_MSFT_1d_fm_split_2023-01-01_train_41d_test_1y_horizon_21
run_timestamp: 2025-09-28_20-18-22
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-09-28_20-18-22_MSFT_1d_fm_split_2023-01-01_train_41d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 325.04722721200517
  mae: 13.489504468935532
  rmse: 18.02906617692678
  mape: 4.366789668619515
