experiment_config_name: 2025-11-17_16-18-03_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_1
run_timestamp: 2025-11-17_16-18-03
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-11-17_16-18-03_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 26.465532394202317
  mae: 3.9270481689453125
  rmse: 5.144466191375186
  mape: 1.2845631176538082
  smape: 1.289216558951985
  mean_directional_accuracy: 100.0
