experiment_config_name: 2025-09-28_20-06-28_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_5
run_timestamp: 2025-09-28_20-06-28
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-09-28_20-06-28_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 66.21907983579902
  mae: 6.38130629292165
  rmse: 8.137510665787113
  mape: 2.124755082569613
