experiment_config_name: 2025-09-28_20-19-40_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_21
run_timestamp: 2025-09-28_20-19-40
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 193
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-09-28_20-19-40_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 285.16466423219606
  mae: 12.46635405717314
  rmse: 16.886819245559423
  mape: 4.044080916963581
