experiment_config_name: 2025-09-15_12-48-22_MSFT_1d_fm_split_2023-01-01_train_41d_test_1y_horizon_1
run_timestamp: 2025-09-15_12-48-22
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-09-15_12-48-22_MSFT_1d_fm_split_2023-01-01_train_41d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 25.26571187771503
  mae: 3.879203888854987
  rmse: 5.0265009576956245
  mape: 1.2888281195217879
