experiment_config_name: 2025-09-28_20-09-22_MSFT_1d_fm_split_2023-01-01_train_249d_test_1y_horizon_5
run_timestamp: 2025-09-28_20-09-22
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-09-28_20-09-22_MSFT_1d_fm_split_2023-01-01_train_249d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 66.22466281095646
  mae: 6.315613041887813
  rmse: 8.137853698055554
  mape: 2.1015093599786034
