experiment_config_name: 2025-09-28_20-24-06_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_63
run_timestamp: 2025-09-28_20-24-06
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/fm/train-less-year-log/2025-09-28_20-24-06_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1498.3905165573633
  mae: 29.819357699369746
  rmse: 38.70904954345125
  mape: 9.23323472731049
