experiment_config_name: 2025-11-30_10-31-07_MSFT_1h_sundial_split_2022-03-31_train_249d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-31-07
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 249
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-market-downturn-2022-log-pct/2025-11-30_10-31-07_MSFT_1h_sundial_split_2022-03-31_train_249d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.690661535405681e-05
  mae: 0.006076631259477199
  rmse: 0.008179646407642375
  mape: 148.24714183126338
  smape: 168.6585414516512
  mean_directional_accuracy: 45.64459930313589
