experiment_config_name: 2025-11-30_11-16-43_MSFT_1h_chronos_base_split_2008-01-20_train_25d_test_60d_horizon_1
run_timestamp: 2025-11-30_11-16-43
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 25
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/chronos_base/rq3-financial-crisis-2008-log-pct/2025-11-30_11-16-43_MSFT_1h_chronos_base_split_2008-01-20_train_25d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 8.540436722120025e-05
  mae: 0.005886811566613598
  rmse: 0.009241448329196038
  mape: 1377199992527.799
  smape: 160.65258167059542
  mean_directional_accuracy: 50.522648083623686
