experiment_config_name: 2025-10-12_11-43-30_MSFT_1d_fm_split_2023-01-01_train_225d_test_1y_horizon_21
run_timestamp: 2025-10-12_11-43-30
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 225
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-43-30_MSFT_1d_fm_split_2023-01-01_train_225d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026497344569790165
  mae: 0.012315258004459878
  rmse: 0.01627800496676118
  mape: 120.60142214092157
  smape: 168.3495427028205
  mean_directional_accuracy: 49.2
