experiment_config_name: 2025-10-12_11-03-35_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_1
run_timestamp: 2025-10-12_11-03-35
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 75
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-03-35_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00027306224318670116
  mae: 0.012446274361761161
  rmse: 0.0165245950990244
  mape: 145.81729101403087
  smape: 156.35484311849922
  mean_directional_accuracy: 56.00000000000001
