experiment_config_name: 2025-10-12_11-05-19_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_1
run_timestamp: 2025-10-12_11-05-19
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-05-19_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002713112337032901
  mae: 0.012479593571198329
  rmse: 0.016471527971117013
  mape: 132.88273255192573
  smape: 162.0739129643903
  mean_directional_accuracy: 52.0
