experiment_config_name: 2025-10-12_11-50-56_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_63
run_timestamp: 2025-10-12_11-50-56
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 75
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-50-56_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002647400857554091
  mae: 0.012378945718633306
  rmse: 0.01627083543507859
  mape: 117.58612968755845
  smape: 169.03930049029958
  mean_directional_accuracy: 51.6
