experiment_config_name: 2025-11-17_18-57-39_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_21
run_timestamp: 2025-11-17_18-57-39
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 75
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-linear-pct/2025-11-17_18-57-39_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002771306200363398
  mae: 0.012406729016222064
  rmse: 0.01664724061327702
  mape: 129.7491991666643
  smape: 164.293634580817
  mean_directional_accuracy: 52.0
