experiment_config_name: 2025-11-17_18-54-11_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_5
run_timestamp: 2025-11-17_18-54-11
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-linear-pct/2025-11-17_18-54-11_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002820577819232067
  mae: 0.012470198072503231
  rmse: 0.016794575967353467
  mape: 115.93136529431412
  smape: 167.7041262950501
  mean_directional_accuracy: 49.6
