experiment_config_name: 2025-11-17_18-51-36_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_5
run_timestamp: 2025-11-17_18-51-36
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 75
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-linear-pct/2025-11-17_18-51-36_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002804557112866875
  mae: 0.012575329803457528
  rmse: 0.01674681197382617
  mape: 139.9859910123491
  smape: 158.37767204372753
  mean_directional_accuracy: 52.0
