experiment_config_name: 2025-10-12_11-08-49_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_1
run_timestamp: 2025-10-12_11-08-49
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 150
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-08-49_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000270423314370826
  mae: 0.012449097205764733
  rmse: 0.01644455272638408
  mape: 124.93009203014273
  smape: 161.8046911651848
  mean_directional_accuracy: 51.6
