experiment_config_name: 2025-10-12_11-51-27_MSFT_1d_fm_split_2023-01-01_train_125d_test_1y_horizon_63
run_timestamp: 2025-10-12_11-51-27
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-51-27_MSFT_1d_fm_split_2023-01-01_train_125d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002658090171188997
  mae: 0.01239875321366284
  rmse: 0.016303650423107694
  mape: 115.5224912159722
  smape: 173.10363165929928
  mean_directional_accuracy: 49.6
