experiment_config_name: 2025-11-17_18-46-45_MSFT_1d_fm_split_2023-01-01_train_225d_test_1y_horizon_1
run_timestamp: 2025-11-17_18-46-45
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 225
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-linear-pct/2025-11-17_18-46-45_MSFT_1d_fm_split_2023-01-01_train_225d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00028300714010138595
  mae: 0.012520305043828917
  rmse: 0.016822816057408044
  mape: 122.19411509025345
  smape: 165.52930449940993
  mean_directional_accuracy: 47.199999999999996
