experiment_config_name: 2025-11-20_07-59-25_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_1
run_timestamp: 2025-11-20_07-59-25
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-11-20_07-59-25_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002861831646523849
  mae: 0.012598761943412248
  rmse: 0.016916949034988103
  mape: 152.39665077433054
  smape: 160.0350880527231
  mean_directional_accuracy: 50.8
