experiment_config_name: 2025-10-12_11-40-18_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_21
run_timestamp: 2025-10-12_11-40-18
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 75
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-40-18_MSFT_1d_fm_split_2023-01-01_train_75d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026500278389116126
  mae: 0.012375002855022781
  rmse: 0.01627890610241245
  mape: 127.56882113088818
  smape: 166.36584671445678
  mean_directional_accuracy: 52.800000000000004
