experiment_config_name: 2025-10-12_11-51-12_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_63
run_timestamp: 2025-10-12_11-51-12
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-51-12_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002627448712560179
  mae: 0.012367713972038312
  rmse: 0.01620940687551577
  mape: 118.40775252213818
  smape: 173.19174197363657
  mean_directional_accuracy: 48.8
