experiment_config_name: 2025-10-12_11-30-48_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_5
run_timestamp: 2025-10-12_11-30-48
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 150
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-30-48_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002748096919332178
  mae: 0.012546330335878493
  rmse: 0.016577384954606617
  mape: 119.36860268167555
  smape: 162.64676202613924
  mean_directional_accuracy: 50.8
