experiment_config_name: 2025-10-12_11-10-34_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_1
run_timestamp: 2025-10-12_11-10-34
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-10-34_MSFT_1d_fm_split_2023-01-01_train_175d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000268977216938868
  mae: 0.012434704329113023
  rmse: 0.016400524898272862
  mape: 121.8524345914826
  smape: 165.86001415422533
  mean_directional_accuracy: 49.6
