experiment_config_name: 2025-11-17_18-58-57_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_21
run_timestamp: 2025-11-17_18-58-57
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 150
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-linear-pct/2025-11-17_18-58-57_MSFT_1d_fm_split_2023-01-01_train_150d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00027858107580322727
  mae: 0.012465554070169504
  rmse: 0.016690748209808547
  mape: 134.83683361252335
  smape: 165.594353859432
  mean_directional_accuracy: 49.6
