experiment_config_name: 2025-10-12_11-29-45_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_5
run_timestamp: 2025-10-12_11-29-45
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-linear-pct/2025-10-12_11-29-45_MSFT_1d_fm_split_2023-01-01_train_100d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00028521371749085
  mae: 0.012801256065749778
  rmse: 0.016888271595721392
  mape: 131.50792676951914
  smape: 157.968205276548
  mean_directional_accuracy: 51.6
