experiment_config_name: 2025-11-17_09-33-51_MSFT_1d_arima_split_2023-01-01_train_225d_test_1y_horizon_1
run_timestamp: 2025-11-17_09-33-51
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 225
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/arima/train-less-year-linear-pct/2025-11-17_09-33-51_MSFT_1d_arima_split_2023-01-01_train_225d_test_1y_horizon_1.csv
arima_order: (0, 0, 0)
evaluation_metrics:
  mse: 0.00027567916405776843
  mae: 0.012326285702964488
  rmse: 0.016603588890892487
  mape: 100.0
  smape: 200.0
  mean_directional_accuracy: 0.0
