experiment_config_name: 2025-05-08_16-17-02_MSFT_1d_fm_split_2023-01-01_train_249d_test_1y_horizon_21
run_timestamp: 2025-05-08_16-17-02
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year/fm/MSFT/2025-05-08_16-17-02_MSFT_1d_fm_split_2023-01-01_train_249d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 186.23953623485392
  mae: 10.690723822954652
  rmse: 13.646960695878548
  mape: 3.5885431047735166
