experiment_config_name: 2025-10-12_11-48-54_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_63
run_timestamp: 2025-10-12_11-48-54
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_11-48-54_MSFT_1d_fm_split_2023-01-01_train_69d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026733593028120206
  mae: 0.012454231395818922
  rmse: 0.016350410706804954
  mape: 119.03311736600588
  smape: 171.4571081826488
  mean_directional_accuracy: 49.2
