experiment_config_name: 2025-10-12_10-54-53_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_1
run_timestamp: 2025-10-12_10-54-53
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_10-54-53_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002704781787860374
  mae: 0.012453194863197938
  rmse: 0.016446220805584406
  mape: 124.44210605630126
  smape: 162.13825880956387
  mean_directional_accuracy: 51.2
