experiment_config_name: 2025-10-12_11-49-55_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_63
run_timestamp: 2025-10-12_11-49-55
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 193
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_11-49-55_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026414856440645546
  mae: 0.012361465069897657
  rmse: 0.016252647919845414
  mape: 113.52507267221301
  smape: 172.37590382644743
  mean_directional_accuracy: 50.0
