experiment_config_name: 2025-10-12_11-47-51_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_63
run_timestamp: 2025-10-12_11-47-51
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_11-47-51_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003554867662061516
  mae: 0.01416651721419331
  rmse: 0.01885435669032894
  mape: 183.58564349653503
  smape: 156.1131561645795
  mean_directional_accuracy: 52.800000000000004
