experiment_config_name: 2025-10-12_10-56-37_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_1
run_timestamp: 2025-10-12_10-56-37
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 193
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_10-56-37_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002686057362269591
  mae: 0.01242641307120674
  rmse: 0.01638919571629307
  mape: 124.86680582983311
  smape: 163.30020731945456
  mean_directional_accuracy: 48.4
