experiment_config_name: 2025-10-12_10-47-56_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_1
run_timestamp: 2025-10-12_10-47-56
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_10-47-56_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000273591777532693
  mae: 0.012393953001999677
  rmse: 0.016540609950442972
  mape: 135.31243571810393
  smape: 155.56749125712946
  mean_directional_accuracy: 52.0
