experiment_config_name: 2025-11-17_18-31-49_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_63
run_timestamp: 2025-11-17_18-31-49
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 193
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-log-pct/2025-11-17_18-31-49_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002766346398967101
  mae: 0.012461244910111122
  rmse: 0.016632337174814313
  mape: 117.18508082192668
  smape: 172.96798942275404
  mean_directional_accuracy: 48.4
