experiment_config_name: 2025-11-17_18-24-18_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_21
run_timestamp: 2025-11-17_18-24-18
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-less-year-log-pct/2025-11-17_18-24-18_MSFT_1d_fm_split_2023-01-01_train_25d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002783178896632154
  mae: 0.012368369843928135
  rmse: 0.016682862154415095
  mape: 133.48922253674618
  smape: 155.82597767602485
  mean_directional_accuracy: 54.400000000000006
