experiment_config_name: 2025-10-12_11-25-31_MSFT_1d_fm_split_2023-01-01_train_89d_test_1y_horizon_5
run_timestamp: 2025-10-12_11-25-31
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 89
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_11-25-31_MSFT_1d_fm_split_2023-01-01_train_89d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002811041023386271
  mae: 0.012745916524998
  rmse: 0.01676615943913892
  mape: 127.87952595204605
  smape: 159.6152095046171
  mean_directional_accuracy: 51.6
