experiment_config_name: 2025-11-20_07-41-13_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_1
run_timestamp: 2025-11-20_07-41-13
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-11-20_07-41-13_MSFT_1d_fm_split_2023-01-01_train_53d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002875468982676219
  mae: 0.012541368634742764
  rmse: 0.016957207855883054
  mape: 159.10977791442852
  smape: 156.81336551266781
  mean_directional_accuracy: 52.800000000000004
