experiment_config_name: 2025-10-12_10-51-25_MSFT_1d_fm_split_2023-01-01_train_89d_test_1y_horizon_1
run_timestamp: 2025-10-12_10-51-25
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 89
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_10-51-25_MSFT_1d_fm_split_2023-01-01_train_89d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002724232563437567
  mae: 0.012409597644832317
  rmse: 0.01650524935721229
  mape: 131.88563265514316
  smape: 159.73132988191938
  mean_directional_accuracy: 54.400000000000006
