experiment_config_name: 2025-11-20_07-48-30_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_1
run_timestamp: 2025-11-20_07-48-30
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-11-20_07-48-30_MSFT_1d_fm_split_2023-01-01_train_149d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00028620318708064753
  mae: 0.012603472927872788
  rmse: 0.016917540810668895
  mape: 138.67422281118584
  smape: 160.87727587607841
  mean_directional_accuracy: 50.4
