experiment_config_name: 2025-10-12_11-39-04_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_21
run_timestamp: 2025-10-12_11-39-04
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 193
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-less-year-log-pct/2025-10-12_11-39-04_MSFT_1d_fm_split_2023-01-01_train_193d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002631874111336535
  mae: 0.012309689412138154
  rmse: 0.016223051844016696
  mape: 122.48331302716382
  smape: 165.71038846923307
  mean_directional_accuracy: 50.4
