experiment_config_name: 2025-05-08_17-28-44_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_5
run_timestamp: 2025-05-08_17-28-44
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-log/arima/MSFT/2025-05-08_17-28-44_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_5.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 1007.2498107204078
  mae: 27.16712900701345
  rmse: 31.737199163133596
  mape: 8.4091470119549
