experiment_config_name: 2025-06-04_14-09-08_MSFT_1d_arima_split_2023-01-01_train_249d_test_1y_horizon_63
run_timestamp: 2025-06-04_14-09-08
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year-log/arima/MSFT/2025-06-04_14-09-08_MSFT_1d_arima_split_2023-01-01_train_249d_test_1y_horizon_63.csv
arima_order: (0, 1, 0)
evaluation_metrics:
  mse: 870.2275802308502
  mae: 23.067442297665025
  rmse: 29.499620001465278
  mape: 7.207376361821065
