experiment_config_name: 2025-05-08_17-28-40_MSFT_1d_arima_split_2023-01-01_train_25d_test_1y_horizon_5
run_timestamp: 2025-05-08_17-28-40
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-log/arima/MSFT/2025-05-08_17-28-40_MSFT_1d_arima_split_2023-01-01_train_25d_test_1y_horizon_5.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 1357.8694984290873
  mae: 32.16417841952067
  rmse: 36.84928084005287
  mape: 9.940405887094427
