experiment_config_name: 2025-10-13_15-27-03_MSFT_1h_sundial_split_2023-01-01_train_100d_test_1y_horizon_1
run_timestamp: 2025-10-13_15-27-03
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 100
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/sundial/train-less-year-linear-pct/2025-10-13_15-27-03_MSFT_1h_sundial_split_2023-01-01_train_100d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.66339505896005e-05
  mae: 0.004050062263361158
  rmse: 0.0060525986641772715
  mape: 825770469097.8994
  smape: 163.6833388966708
  mean_directional_accuracy: 51.028571428571425
