experiment_config_name: 2025-11-30_09-24-50_MSFT_1h_arima_split_2020-02-28_train_53d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-24-50
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 53
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/arima/rq3-covid-crash-2020-log/2025-11-30_09-24-50_MSFT_1h_arima_split_2020-02-28_train_53d_test_60d_horizon_1.csv
arima_order: (0, 2, 2)
evaluation_metrics:
  mse: 7.165338884900122
  mae: 1.8146600594644506
  rmse: 2.676815063634416
  mape: 1.166398719594091
  smape: 1.1683058970372036
  mean_directional_accuracy: 100.0
