experiment_config_name: 2025-09-28_17-38-41_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_5
run_timestamp: 2025-09-28_17-38-41
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 5
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/arima/train-less-year-log/2025-09-28_17-38-41_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_5.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 444.9325452336145
  mae: 17.52415470174551
  rmse: 21.093424217836574
  mape: 5.470729631486297
