experiment_config_name: 2025-11-17_01-14-59_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_5
run_timestamp: 2025-11-17_01-14-59
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/arima/train-less-year-log/2025-11-17_01-14-59_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_5.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 1067.6686498042607
  mae: 28.007864805245074
  rmse: 32.67519930779705
  mape: 8.55266688925516
  smape: 9.048997636237049
  mean_directional_accuracy: 100.0
