experiment_config_name: 2025-11-17_01-14-42_MSFT_1d_arima_split_2023-01-01_train_41d_test_1y_horizon_5
run_timestamp: 2025-11-17_01-14-42
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/arima/train-less-year-log/2025-11-17_01-14-42_MSFT_1d_arima_split_2023-01-01_train_41d_test_1y_horizon_5.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 1339.0585560251925
  mae: 31.79422176017818
  rmse: 36.59314903127623
  mape: 9.698072395818635
  smape: 10.321756034415193
  mean_directional_accuracy: 100.0
