experiment_config_name: 2025-11-17_01-17-43_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_21
run_timestamp: 2025-11-17_01-17-43
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/arima/train-less-year-log/2025-11-17_01-17-43_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_21.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 2120.226446376262
  mae: 40.39118970892976
  rmse: 46.045916717731465
  mape: 12.295376954854467
  smape: 13.296374521343923
  mean_directional_accuracy: 100.0
