experiment_config_name: 2025-09-15_15-48-27_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_1
run_timestamp: 2025-09-15_15-48-27
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/arima/train-less-year-log/2025-09-15_15-48-27_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_1.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 60.20392305476402
  mae: 6.490500846920286
  rmse: 7.759118703484567
  mape: 2.0770018696315242
