experiment_config_name: 2025-11-18_21-15-00_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_1
run_timestamp: 2025-11-18_21-15-00
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 53
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/arima/train-less-year-log/2025-11-18_21-15-00_MSFT_1d_arima_split_2023-01-01_train_53d_test_1y_horizon_1.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 238.74562661770096
  mae: 13.638738903622572
  rmse: 15.45139562038656
  mape: 4.197283582836121
  smape: 4.305567027521007
  mean_directional_accuracy: 100.0
