experiment_config_name: 2025-11-17_01-18-32_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_21
run_timestamp: 2025-11-17_01-18-32
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/arima/train-less-year-log/2025-11-17_01-18-32_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_21.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 1889.0444031369461
  mae: 37.06098055516083
  rmse: 43.46313844094725
  mape: 11.284629753627105
  smape: 12.18085916580326
  mean_directional_accuracy: 100.0
