experiment_config_name: 2025-11-17_01-21-16_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_63
run_timestamp: 2025-11-17_01-21-16
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/arima/train-less-year-log/2025-11-17_01-21-16_MSFT_1d_arima_split_2023-01-01_train_116d_test_1y_horizon_63.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 3408.3993631248695
  mae: 51.07145856735848
  rmse: 58.38149846590844
  mape: 15.455876979018374
  smape: 17.105033574353882
  mean_directional_accuracy: 100.0
