experiment_config_name: 2025-07-19_22-01-12_MSFT_1d_sundial_split_2023-01-01_train_250d_test_1y_horizon_5
run_timestamp: 2025-07-19_22-01-12
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 250
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 5
differencing_applied: false
results_file_path: results/train-less-year-linear/sundial/MSFT/2025-07-19_22-01-12_MSFT_1d_sundial_split_2023-01-01_train_250d_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 86.40907060657995
  mae: 7.45127074146723
  rmse: 9.295647939040073
  mape: 2.443906755239589
