experiment_config_name: 2025-07-19_22-01-49_MSFT_1d_sundial_split_2023-01-01_train_125d_test_1y_horizon_21
run_timestamp: 2025-07-19_22-01-49
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 21
differencing_applied: false
results_file_path: results/train-less-year-linear/sundial/MSFT/2025-07-19_22-01-49_MSFT_1d_sundial_split_2023-01-01_train_125d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 472.98760918927024
  mae: 16.108202424387176
  rmse: 21.748278304023753
  mape: 5.185861104145449
