experiment_config_name: 2025-07-19_22-02-31_MSFT_1d_sundial_split_2023-01-01_train_75d_test_1y_horizon_63
run_timestamp: 2025-07-19_22-02-31
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 75
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 63
differencing_applied: false
results_file_path: results/train-less-year-linear/sundial/MSFT/2025-07-19_22-02-31_MSFT_1d_sundial_split_2023-01-01_train_75d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 2346.9475397063266
  mae: 35.87244251027166
  rmse: 48.44530461981147
  mape: 10.930767192783536
