experiment_config_name: 2025-11-20_13-07-52_MSFT_1h_fm_split_2023-01-01_train_116d_test_1y_horizon_1
run_timestamp: 2025-11-20_13-07-52
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/train-less-year-log/2025-11-20_13-07-52_MSFT_1h_fm_split_2023-01-01_train_116d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.8408775489898628
  mae: 1.3796053707449785
  rmse: 1.959815692607308
  mape: 0.44561635141617373
  smape: 0.44545847289110835
  mean_directional_accuracy: 100.0
