experiment_config_name: 2025-11-20_13-18-36_MSFT_1h_fm_split_2023-01-01_train_149d_test_1y_horizon_1
run_timestamp: 2025-11-20_13-18-36
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/train-less-year-log/2025-11-20_13-18-36_MSFT_1h_fm_split_2023-01-01_train_149d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.6659238579993296
  mae: 1.3294472467912954
  rmse: 1.9146602461009445
  mape: 0.4305984616703539
  smape: 0.43085561890134777
  mean_directional_accuracy: 100.0
