experiment_config_name: 2025-11-20_12-25-04_MSFT_1h_fm_split_2023-01-01_train_41d_test_1y_horizon_1
run_timestamp: 2025-11-20_12-25-04
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/train-less-year-log/2025-11-20_12-25-04_MSFT_1h_fm_split_2023-01-01_train_41d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.796764553039747
  mae: 1.3682938957868314
  rmse: 1.9485288176056692
  mape: 0.4440054717320759
  smape: 0.44400422973689835
  mean_directional_accuracy: 100.0
