experiment_config_name: 2025-09-08_22-58-46_MSFT_1h_sundial_split_2023-01-01_train_4y_test_1y_horizon_1
run_timestamp: 2025-09-08_22-58-46
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/sundial/train-restricted-years/2025-09-08_22-58-46_MSFT_1h_sundial_split_2023-01-01_train_4y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 25.510248743945684
  mae: 3.529159694824218
  rmse: 5.050767144102536
  mape: 1.24886089341954
