experiment_config_name: 2025-09-28_18-25-58_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_21
run_timestamp: 2025-09-28_18-25-58
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-linear/2025-09-28_18-25-58_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 225.92181387168844
  mae: 10.893299057116582
  rmse: 15.030695721479043
  mape: 3.4937385076413725
