experiment_config_name: 2025-09-28_18-27-57_MSFT_1d_chronos_base_split_2023-01-01_train_50d_test_1y_horizon_63
run_timestamp: 2025-09-28_18-27-57
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 50
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-linear/2025-09-28_18-27-57_MSFT_1d_chronos_base_split_2023-01-01_train_50d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 600.0397116968194
  mae: 19.564908286746558
  rmse: 24.495708026036304
  mape: 6.117430248935853
