experiment_config_name: 2025-11-17_14-43-21_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_63
run_timestamp: 2025-11-17_14-43-21
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-linear/2025-11-17_14-43-21_MSFT_1d_chronos_base_split_2023-01-01_train_125d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1090.3167652286393
  mae: 26.196254580078126
  rmse: 33.019944961017714
  mape: 8.048474358528193
  smape: 8.421879670449218
  mean_directional_accuracy: 100.0
