experiment_config_name: 2025-11-30_10-36-36_MSFT_1h_sundial_split_2020-02-28_train_149d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-36-36
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 149
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-covid-crash-2020-log-pct/2025-11-30_10-36-36_MSFT_1h_sundial_split_2020-02-28_train_149d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003227232175588776
  mae: 0.011901028727482502
  rmse: 0.01796449881179204
  mape: 139.36310930082624
  smape: 161.55731210951504
  mean_directional_accuracy: 51.91637630662021
