experiment_config_name: 2025-11-30_10-33-10_MSFT_1h_sundial_split_2020-02-28_train_41d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-33-10
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 41
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-log-pct/2025-11-30_10-33-10_MSFT_1h_sundial_split_2020-02-28_train_41d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003296859545940445
  mae: 0.011957668617713925
  rmse: 0.018157256251814163
  mape: 152.9125176740341
  smape: 165.3420945421065
  mean_directional_accuracy: 48.08362369337979
