experiment_config_name: 2025-11-17_15-12-45_MSFT_1d_chronos_base_split_2023-01-01_train_149d_test_1y_horizon_21
run_timestamp: 2025-11-17_15-12-45
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-log-pct/2025-11-17_15-12-45_MSFT_1d_chronos_base_split_2023-01-01_train_149d_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002744387812689743
  mae: 0.012355803999372592
  rmse: 0.016566193928267723
  mape: 113.45216359159215
  smape: 171.73806087914545
  mean_directional_accuracy: 49.6
