experiment_config_name: 2025-10-11_23-51-13_MSFT_1d_chronos_base_split_2023-01-01_train_249d_test_1y_horizon_1
run_timestamp: 2025-10-11_23-51-13
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-log-pct/2025-10-11_23-51-13_MSFT_1d_chronos_base_split_2023-01-01_train_249d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026496368783503785
  mae: 0.012297824290307204
  rmse: 0.01627770523860897
  mape: 108.50736806459142
  smape: 175.14343675037952
  mean_directional_accuracy: 51.2
