experiment_config_name: 2025-10-11_23-59-07_MSFT_1d_chronos_base_split_2023-01-01_train_25d_test_1y_horizon_63
run_timestamp: 2025-10-11_23-59-07
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-log-pct/2025-10-11_23-59-07_MSFT_1d_chronos_base_split_2023-01-01_train_25d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002715972814424627
  mae: 0.012735733707382185
  rmse: 0.01648020878030563
  mape: 158.64830311269853
  smape: 169.79917918251223
  mean_directional_accuracy: 46.800000000000004
