experiment_config_name: 2025-11-17_15-13-47_MSFT_1d_chronos_base_split_2023-01-01_train_25d_test_1y_horizon_63
run_timestamp: 2025-11-17_15-13-47
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/chronos_base/train-less-year-log-pct/2025-11-17_15-13-47_MSFT_1d_chronos_base_split_2023-01-01_train_25d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002819735868610591
  mae: 0.012709145899559867
  rmse: 0.01679206916556322
  mape: 147.72053824912322
  smape: 167.3693500443844
  mean_directional_accuracy: 51.2
