experiment_config_name: 2025-06-09_00-02-59_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_21
run_timestamp: 2025-06-09_00-02-59
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: results/train-restricted-years/fm/MSFT/2025-06-09_00-02-59_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 201.24653440950502
  mae: 10.102777364567123
  rmse: 14.186138812570002
  mape: 3.240562684328003
