experiment_config_name: 2025-06-04_13-38-54_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_1
run_timestamp: 2025-06-04_13-38-54
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: results/train-restricted-years/fm/MSFT/2025-06-04_13-38-54_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 1.4463868421452453
  mae: 0.9401139227764332
  rmse: 1.2026582399606487
  mape: 0.3085762761825758
