experiment_config_name: 2025-06-09_00-05-11_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_63
run_timestamp: 2025-06-09_00-05-11
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
results_file_path: results/train-restricted-years/fm/MSFT/2025-06-09_00-05-11_MSFT_1d_fm_split_2023-01-01_train_2y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1041.0370079587083
  mae: 24.172002213531012
  rmse: 32.265105113089405
  mape: 7.439891212758109
