experiment_config_name: 2025-06-09_00-05-01_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_63
run_timestamp: 2025-06-09_00-05-01
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 1.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
results_file_path: results/train-restricted-years/fm/MSFT/2025-06-09_00-05-01_MSFT_1d_fm_split_2023-01-01_train_1y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 1013.8269044363119
  mae: 24.065113796785518
  rmse: 31.840648618335525
  mape: 7.432170838395567
