experiment_config_name: 2025-06-04_14-05-21_MSFT_1d_fm_split_2023-01-01_train_10y_test_1y_horizon_21
run_timestamp: 2025-06-04_14-05-21
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
results_file_path: results/train-restricted-years/fm/MSFT/2025-06-04_14-05-21_MSFT_1d_fm_split_2023-01-01_train_10y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 258.7297414630257
  mae: 13.199597875069227
  rmse: 16.08507822371485
  mape: 4.447951881304015
