experiment_config_name: 2025-11-20_22-56-06_MSFT_1h_chronos_base_split_2023-01-01_train_32d_test_1y_horizon_1
run_timestamp: 2025-11-20_22-56-06
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 32
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/chronos_base/train-less-year-log/2025-11-20_22-56-06_MSFT_1h_chronos_base_split_2023-01-01_train_32d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 4.599337421848456
  mae: 1.552014090401786
  rmse: 2.144606589062072
  mape: 0.49947920290326786
  smape: 0.4991604100696926
  mean_directional_accuracy: 100.0
