experiment_config_name: 2025-11-19_13-51-53_MSFT_1h_sundial_split_2023-01-01_train_10y_test_1y_horizon_1
run_timestamp: 2025-11-19_13-51-53
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/train-restricted-years-pct/2025-11-19_13-51-53_MSFT_1h_sundial_split_2023-01-01_train_10y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.641658533284128e-05
  mae: 0.0040296843224624105
  rmse: 0.006034615591140937
  mape: 878432668998.7236
  smape: 171.87876871831924
  mean_directional_accuracy: 49.48571428571429
