experiment_config_name: 2025-11-19_14-48-20_MSFT_1h_sundial_split_2023-01-01_train_249d_test_1y_horizon_1
run_timestamp: 2025-11-19_14-48-20
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 249
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/train-less-year-log-pct/2025-11-19_14-48-20_MSFT_1h_sundial_split_2023-01-01_train_249d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.6754888538232704e-05
  mae: 0.004055203643017458
  rmse: 0.006062581012921205
  mape: 777662901354.3015
  smape: 167.59035437867962
  mean_directional_accuracy: 49.65714285714286
