experiment_config_name: 2025-09-29_00-45-39_MSFT_1h_sundial_split_2023-01-01_train_69d_test_1y_horizon_1
run_timestamp: 2025-09-29_00-45-39
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 69
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/sundial/train-less-year-log/2025-09-29_00-45-39_MSFT_1h_sundial_split_2023-01-01_train_69d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.5818967511931614
  mae: 1.3066025020926344
  rmse: 1.8925899585470598
  mape: 0.4236163285760776
