experiment_config_name: 2025-11-30_18-31-30_MSFT_1h_fm_split_2020-02-28_train_25d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-31-30
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 25
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/rq3-covid-crash-2020-log-pct/2025-11-30_18-31-30_MSFT_1h_fm_split_2020-02-28_train_25d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003469855211506013
  mae: 0.012297836808234704
  rmse: 0.01862754737346281
  mape: 136.828479048595
  smape: 164.59081131846227
  mean_directional_accuracy: 46.68989547038328
