experiment_config_name: 2025-11-30_18-34-06_MSFT_1h_fm_split_2020-02-28_train_41d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-34-06
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 41
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/rq3-covid-crash-2020-log-pct/2025-11-30_18-34-06_MSFT_1h_fm_split_2020-02-28_train_41d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003463216424474935
  mae: 0.0123094872207549
  rmse: 0.018609719031933113
  mape: 140.33324327760474
  smape: 163.5570068118742
  mean_directional_accuracy: 45.64459930313589
