experiment_config_name: 2025-11-30_18-38-03_MSFT_1h_fm_split_2020-02-28_train_89d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-38-03
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 89
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/rq3-covid-crash-2020-log-pct/2025-11-30_18-38-03_MSFT_1h_fm_split_2020-02-28_train_89d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00033765202111727424
  mae: 0.012109176157186185
  rmse: 0.01837531009581265
  mape: 132.30710660435773
  smape: 168.79362016566736
  mean_directional_accuracy: 48.43205574912892
