experiment_config_name: 2025-11-30_10-55-54_MSFT_1h_sundial_split_2020-02-28_train_125d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-55-54
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 125
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-linear-pct/2025-11-30_10-55-54_MSFT_1h_sundial_split_2020-02-28_train_125d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000323442868156015
  mae: 0.011768277831271422
  rmse: 0.017984517456857578
  mape: 125.97862133089794
  smape: 160.36676491173367
  mean_directional_accuracy: 52.961672473867594
