experiment_config_name: 2025-11-30_10-56-37_MSFT_1h_sundial_split_2020-02-28_train_150d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-56-37
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 150
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-linear-pct/2025-11-30_10-56-37_MSFT_1h_sundial_split_2020-02-28_train_150d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00032762251489791924
  mae: 0.011952602777636937
  rmse: 0.018100345712110562
  mape: 132.97379360236948
  smape: 165.25144804823276
  mean_directional_accuracy: 47.386759581881535
