experiment_config_name: 2025-11-30_10-55-11_MSFT_1h_sundial_split_2020-02-28_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_10-55-11
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-linear-pct/2025-11-30_10-55-11_MSFT_1h_sundial_split_2020-02-28_train_100d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0003220191163603997
  mae: 0.011726512331968041
  rmse: 0.017944891093578687
  mape: 113.15494204066765
  smape: 158.20394574766138
  mean_directional_accuracy: 54.35540069686411
