experiment_config_name: 2025-11-30_09-42-16_MSFT_1h_sundial_split_2022-03-31_train_25d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-42-16
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 25
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-market-downturn-2022-log/2025-11-30_09-42-16_MSFT_1h_sundial_split_2022-03-31_train_25d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 5.5774332192851785
  mae: 1.7853799342776842
  rmse: 2.361658997248582
  mape: 0.6455094615738749
  smape: 0.6443597055813947
  mean_directional_accuracy: 100.0
