experiment_config_name: 2025-11-30_09-44-55_MSFT_1h_sundial_split_2022-03-31_train_69d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-44-55
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 69
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-market-downturn-2022-log/2025-11-30_09-44-55_MSFT_1h_sundial_split_2022-03-31_train_69d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 5.572974176169626
  mae: 1.8101220447925734
  rmse: 2.360714759594989
  mape: 0.6549290926721707
  smape: 0.6537094976953249
  mean_directional_accuracy: 100.0
