experiment_config_name: 2025-10-12_20-51-48_MSFT_1h_fm_split_2023-01-01_train_175d_test_1y_horizon_1
run_timestamp: 2025-10-12_20-51-48
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/train-less-year-linear-pct/2025-10-12_20-51-48_MSFT_1h_fm_split_2023-01-01_train_175d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.65787136734281e-05
  mae: 0.004049165489498257
  rmse: 0.006048033868409477
  mape: 563757007439.5221
  smape: 171.59412792469118
  mean_directional_accuracy: 48.68571428571429
