experiment_config_name: 2025-11-30_09-34-14_MSFT_1h_arima_split_2020-02-28_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-34-14
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/arima/rq3-covid-crash-2020-linear-pct/2025-11-30_09-34-14_MSFT_1h_arima_split_2020-02-28_train_100d_test_60d_horizon_1.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 0.00030309023190606304
  mae: 0.011630944041616204
  rmse: 0.01740948683637927
  mape: 155.40252467863866
  smape: 151.5448656829234
  mean_directional_accuracy: 51.91637630662021
