experiment_config_name: 2025-11-17_09-20-01_MSFT_1d_arima_split_2023-01-01_train_10y_test_1y_horizon_63
run_timestamp: 2025-11-17_09-20-01
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/arima/train-restricted-years-pct/2025-11-17_09-20-01_MSFT_1d_arima_split_2023-01-01_train_10y_test_1y_horizon_63.csv
arima_order: (1, 0, 1)
evaluation_metrics:
  mse: 0.00027279647701453606
  mae: 0.012258713410780359
  rmse: 0.016516551607842846
  mape: 108.78904204167182
  smape: 171.39522960295315
  mean_directional_accuracy: 54.0
