experiment_config_name: 2025-11-17_09-15-08_MSFT_1d_arima_split_2023-01-01_train_4y_test_1y_horizon_21
run_timestamp: 2025-11-17_09-15-08
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/arima/train-restricted-years-pct/2025-11-17_09-15-08_MSFT_1d_arima_split_2023-01-01_train_4y_test_1y_horizon_21.csv
arima_order: (0, 0, 3)
evaluation_metrics:
  mse: 0.00027225669825477606
  mae: 0.012260661171665277
  rmse: 0.01650020297616899
  mape: 109.91938358303123
  smape: 170.21110388648486
  mean_directional_accuracy: 54.800000000000004
