experiment_config_name: 2025-10-11_22-33-32_MSFT_1d_arima_split_2023-01-01_train_6y_test_1y_horizon_1
run_timestamp: 2025-10-11_22-33-32
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_years: 1
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/arima/train-restricted-years-pct/2025-10-11_22-33-32_MSFT_1d_arima_split_2023-01-01_train_6y_test_1y_horizon_1.csv
arima_order: (0, 0, 2)
evaluation_metrics:
  mse: 0.00025526191816168433
  mae: 0.012100269140590439
  rmse: 0.01597691829364112
  mape: 112.48878876161021
  smape: 167.1917022429344
  mean_directional_accuracy: 51.2
