experiment_config_name: 2025-11-20_01-26-19_MSFT_1h_arima_split_2023-01-01_train_7y_test_1y_horizon_1
run_timestamp: 2025-11-20_01-26-19
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/arima/train-restricted-years-pct/2025-11-20_01-26-19_MSFT_1h_arima_split_2023-01-01_train_7y_test_1y_horizon_1.csv
arima_order: (0, 0, 2)
evaluation_metrics:
  mse: 3.623278836726857e-05
  mae: 0.00400683871442
  rmse: 0.0060193677713916574
  mape: 378444851783.37915
  smape: 174.94279242161892
  mean_directional_accuracy: 50.62857142857143
