experiment_config_name: 2025-11-20_13-50-54_MSFT_1h_fm_split_2023-01-01_train_25d_test_1y_horizon_1
run_timestamp: 2025-11-20_13-50-54
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/train-less-year-linear/2025-11-20_13-50-54_MSFT_1h_fm_split_2023-01-01_train_25d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.8698439623890946
  mae: 1.3859206563895095
  rmse: 1.9671918977031941
  mape: 0.4492746129291961
  smape: 0.44937902654898515
  mean_directional_accuracy: 100.0
