experiment_config_name: 2025-10-12_11-19-04_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_5
run_timestamp: 2025-10-12_11-19-04
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-10-12_11-19-04_MSFT_1d_fm_split_2023-01-01_train_4y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026988471265530247
  mae: 0.012328308036734728
  rmse: 0.016428168268413326
  mape: 122.72127461945878
  smape: 158.28417381422244
  mean_directional_accuracy: 54.0
