experiment_config_name: 2025-10-12_11-18-33_MSFT_1d_fm_split_2023-01-01_train_3y_test_1y_horizon_5
run_timestamp: 2025-10-12_11-18-33
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 3.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-10-12_11-18-33_MSFT_1d_fm_split_2023-01-01_train_3y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002686143458910547
  mae: 0.01217649276935053
  rmse: 0.016389458376988995
  mape: 110.86695642548972
  smape: 155.61964067312778
  mean_directional_accuracy: 56.00000000000001
