experiment_config_name: 2025-11-20_07-24-39_MSFT_1d_fm_split_2023-01-01_train_5y_test_1y_horizon_1
run_timestamp: 2025-11-20_07-24-39
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 5.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-11-20_07-24-39_MSFT_1d_fm_split_2023-01-01_train_5y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00027957985465892497
  mae: 0.012411678019442964
  rmse: 0.0167206415743812
  mape: 122.44175412657819
  smape: 163.03874073054513
  mean_directional_accuracy: 52.400000000000006
