experiment_config_name: 2025-11-17_17-58-55_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_63
run_timestamp: 2025-11-17_17-58-55
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-11-17_17-58-55_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002745312898721319
  mae: 0.012336668585143472
  rmse: 0.016568985782845366
  mape: 107.24811463197604
  smape: 175.06306609208508
  mean_directional_accuracy: 48.8
