experiment_config_name: 2025-10-12_11-47-35_MSFT_1d_fm_split_2023-01-01_train_10y_test_1y_horizon_63
run_timestamp: 2025-10-12_11-47-35
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-10-12_11-47-35_MSFT_1d_fm_split_2023-01-01_train_10y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002636460564432034
  mae: 0.0122945032132863
  rmse: 0.016237181296124132
  mape: 107.75914099309276
  smape: 173.67531449275288
  mean_directional_accuracy: 51.2
