experiment_config_name: 2025-10-12_11-20-40_MSFT_1d_fm_split_2023-01-01_train_7y_test_1y_horizon_5
run_timestamp: 2025-10-12_11-20-40
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-10-12_11-20-40_MSFT_1d_fm_split_2023-01-01_train_7y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002705621837071127
  mae: 0.012301336399710308
  rmse: 0.016448774535116974
  mape: 118.72909206779119
  smape: 160.32299189214078
  mean_directional_accuracy: 52.0
