experiment_config_name: 2025-11-17_17-54-24_MSFT_1d_fm_split_2023-01-01_train_7y_test_1y_horizon_21
run_timestamp: 2025-11-17_17-54-24
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-11-17_17-54-24_MSFT_1d_fm_split_2023-01-01_train_7y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00027752553143714736
  mae: 0.012394350703357388
  rmse: 0.01665909755770544
  mape: 121.52081942332285
  smape: 169.6717253639325
  mean_directional_accuracy: 50.8
