experiment_config_name: 2025-11-17_17-36-23_MSFT_1d_fm_split_2023-01-01_train_6y_test_1y_horizon_1
run_timestamp: 2025-11-17_17-36-23
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-restricted-years-pct/2025-11-17_17-36-23_MSFT_1d_fm_split_2023-01-01_train_6y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002792672908260091
  mae: 0.01244395535491931
  rmse: 0.016711292314659842
  mape: 124.27683797590868
  smape: 166.29422310619086
  mean_directional_accuracy: 52.0
