experiment_config_name: 2025-10-12_11-47-05_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_63
run_timestamp: 2025-10-12_11-47-05
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-10-12_11-47-05_MSFT_1d_fm_split_2023-01-01_train_8y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002632838686284983
  mae: 0.012293852331205637
  rmse: 0.016226024424624112
  mape: 108.0668428658641
  smape: 174.57149475744356
  mean_directional_accuracy: 49.2
