experiment_config_name: 2025-10-12_11-20-08_MSFT_1d_fm_split_2023-01-01_train_6y_test_1y_horizon_5
run_timestamp: 2025-10-12_11-20-08
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-10-12_11-20-08_MSFT_1d_fm_split_2023-01-01_train_6y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026930345638396847
  mae: 0.012342551866433345
  rmse: 0.016410467890464565
  mape: 118.83410281692484
  smape: 163.03854413796344
  mean_directional_accuracy: 52.0
