experiment_config_name: 2025-10-12_11-34-04_MSFT_1d_fm_split_2023-01-01_train_3y_test_1y_horizon_21
run_timestamp: 2025-10-12_11-34-04
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 3.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 21
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-10-12_11-34-04_MSFT_1d_fm_split_2023-01-01_train_3y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.00026555826711042557
  mae: 0.012326333638697753
  rmse: 0.01629595861281028
  mape: 113.69144764622344
  smape: 171.61747052698092
  mean_directional_accuracy: 51.2
