experiment_config_name: 2025-11-17_17-48-32_MSFT_1d_fm_split_2023-01-01_train_6y_test_1y_horizon_5
run_timestamp: 2025-11-17_17-48-32
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 5
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1d/fm/train-restricted-years-pct/2025-11-17_17-48-32_MSFT_1d_fm_split_2023-01-01_train_6y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0002788311763900179
  mae: 0.012423299435378773
  rmse: 0.016698238721195056
  mape: 129.0897898066747
  smape: 161.9912863241549
  mean_directional_accuracy: 54.800000000000004
