experiment_config_name: 2025-11-17_17-59-19_MSFT_1d_fm_split_2023-01-01_train_9y_test_1y_horizon_63
run_timestamp: 2025-11-17_17-59-19
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 9.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 63
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1d/fm/train-restricted-years-pct/2025-11-17_17-59-19_MSFT_1d_fm_split_2023-01-01_train_9y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.000274740437378268
  mae: 0.012345526494127883
  rmse: 0.016575295996701475
  mape: 107.04137023382326
  smape: 174.53542409014233
  mean_directional_accuracy: 48.0
