experiment_config_name: 2025-11-30_09-30-35_MSFT_1h_arima_split_2020-02-28_train_53d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-30-35
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 53
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/arima/rq3-covid-crash-2020-log-pct/2025-11-30_09-30-35_MSFT_1h_arima_split_2020-02-28_train_53d_test_60d_horizon_1.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 0.0003109471376965727
  mae: 0.01179148924840061
  rmse: 0.01763369325174317
  mape: 152.7955418634278
  smape: 149.5193788760138
  mean_directional_accuracy: 55.052264808362374
