experiment_config_name: 2025-11-30_09-30-18_MSFT_1h_arima_split_2020-02-28_train_32d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-30-18
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 32
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/arima/rq3-covid-crash-2020-log-pct/2025-11-30_09-30-18_MSFT_1h_arima_split_2020-02-28_train_32d_test_60d_horizon_1.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 0.0003074009461082959
  mae: 0.011687822160381084
  rmse: 0.01753285333618849
  mape: 153.5219076685114
  smape: 148.3301428006687
  mean_directional_accuracy: 53.65853658536586
