experiment_config_name: 2025-11-30_11-05-21_MSFT_1h_chronos_base_split_2022-03-31_train_249d_test_60d_horizon_1
run_timestamp: 2025-11-30_11-05-21
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 249
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/chronos_base/rq3-market-downturn-2022-log/2025-11-30_11-05-21_MSFT_1h_chronos_base_split_2022-03-31_train_249d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.056278323460969
  mae: 2.018498654249237
  rmse: 2.6563656230761925
  mape: 0.7323627313130467
  smape: 0.7350442351374548
  mean_directional_accuracy: 100.0
