experiment_config_name: 2025-11-30_11-04-50_MSFT_1h_chronos_base_split_2022-03-31_train_149d_test_60d_horizon_1
run_timestamp: 2025-11-30_11-04-50
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 149
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/chronos_base/rq3-market-downturn-2022-log/2025-11-30_11-04-50_MSFT_1h_chronos_base_split_2022-03-31_train_149d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.329602774535591
  mae: 1.9079045482462698
  rmse: 2.5158701823694303
  mape: 0.6899081439793494
  smape: 0.6918768323784189
  mean_directional_accuracy: 100.0
