experiment_config_name: 2025-09-01_21-09-32_MSFT_1h_fm_split_2023-01-01_train_4y_test_1y_horizon_1
run_timestamp: 2025-09-01_21-09-32
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 4.0
training_period_unit: years
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/train-restricted-years/2025-09-01_21-09-32_MSFT_1h_fm_split_2023-01-01_train_4y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.915490699879002
  mae: 1.40099291608538
  rmse: 1.9787598893951237
  mape: 0.4564186394289614
