experiment_config_name: 2025-11-17_14-12-07_MSFT_1d_chronos_base_split_2023-01-01_train_10y_test_1y_horizon_21
run_timestamp: 2025-11-17_14-12-07
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 10.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/chronos_base/train-restricted-years/2025-11-17_14-12-07_MSFT_1d_chronos_base_split_2023-01-01_train_10y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 177.13357115625647
  mae: 10.10543248535156
  rmse: 13.309153660404423
  mape: 3.266972862913964
  smape: 3.3299323073606555
  mean_directional_accuracy: 100.0
