experiment_config_name: 2025-11-17_14-09-29_MSFT_1d_chronos_base_split_2023-01-01_train_2y_test_1y_horizon_21
run_timestamp: 2025-11-17_14-09-29
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 2.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/chronos_base/train-restricted-years/2025-11-17_14-09-29_MSFT_1d_chronos_base_split_2023-01-01_train_2y_test_1y_horizon_21.csv
arima_order: N/A
evaluation_metrics:
  mse: 199.20925073933245
  mae: 10.634218103027342
  rmse: 14.114150726817837
  mape: 3.3920024736577292
  smape: 3.450708944080192
  mean_directional_accuracy: 100.0
