experiment_config_name: 2025-09-15_16-44-58_MSFT_1d_chronos_base_split_2023-01-01_train_7y_test_1y_horizon_1
run_timestamp: 2025-09-15_16-44-58
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-restricted-years/2025-09-15_16-44-58_MSFT_1d_chronos_base_split_2023-01-01_train_7y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 30.390405788869895
  mae: 4.321120619611945
  rmse: 5.5127493856396095
  mape: 1.4324233018715602
