experiment_config_name: 2025-11-18_22-04-12_MSFT_1d_chronos_base_split_2023-01-01_train_6y_test_1y_horizon_1
run_timestamp: 2025-11-18_22-04-12
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/chronos_base/train-restricted-years/2025-11-18_22-04-12_MSFT_1d_chronos_base_split_2023-01-01_train_6y_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 32.23862861344364
  mae: 4.4443851855468735
  rmse: 5.677907062769136
  mape: 1.4564696490785538
  smape: 1.4600377027131148
  mean_directional_accuracy: 100.0
