experiment_config_name: 2025-11-17_14-08-09_MSFT_1d_chronos_base_split_2023-01-01_train_8y_test_1y_horizon_5
run_timestamp: 2025-11-17_14-08-09
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: chronos_base
horizon_length: 5
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/chronos_base/train-restricted-years/2025-11-17_14-08-09_MSFT_1d_chronos_base_split_2023-01-01_train_8y_test_1y_horizon_5.csv
arima_order: N/A
evaluation_metrics:
  mse: 74.86487307456794
  mae: 6.967437890624999
  rmse: 8.652448963996722
  mape: 2.2810579779811344
  smape: 2.290146235327599
  mean_directional_accuracy: 100.0
