experiment_config_name: 2025-09-28_18-26-37_MSFT_1d_chronos_base_split_2023-01-01_train_3y_test_1y_horizon_63
run_timestamp: 2025-09-28_18-26-37
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 3.0
training_period_unit: years
test_period_years: 1
forecasting_method: chronos_base
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/chronos_base/train-restricted-years/2025-09-28_18-26-37_MSFT_1d_chronos_base_split_2023-01-01_train_3y_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 616.8894076252582
  mae: 20.48355597980939
  rmse: 24.837258456304273
  mape: 6.582752646891664
