experiment_config_name: 2025-11-30_18-59-11_MSFT_1h_fm_split_2022-03-31_train_50d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-59-11
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 50
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/rq3-market-downturn-2022-linear-pct/2025-11-30_18-59-11_MSFT_1h_fm_split_2022-03-31_train_50d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.597900514698562e-05
  mae: 0.005954260818941309
  rmse: 0.008122746157980417
  mape: 132.75085298822938
  smape: 161.98392318499418
  mean_directional_accuracy: 51.56794425087108
