experiment_config_name: 2025-11-20_18-41-14_MSFT_1h_fm_split_2023-01-01_train_149d_test_1y_horizon_1
run_timestamp: 2025-11-20_18-41-14
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 149
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/train-less-year-log-pct/2025-11-20_18-41-14_MSFT_1h_fm_split_2023-01-01_train_149d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.654851180975162e-05
  mae: 0.004050080808909034
  rmse: 0.006045536519594569
  mape: 468750254669.8329
  smape: 172.90632749042572
  mean_directional_accuracy: 48.22857142857143
