experiment_config_name: 2025-10-12_18-18-26_MSFT_1h_fm_split_2023-01-01_train_41d_test_1y_horizon_1
run_timestamp: 2025-10-12_18-18-26
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 41
training_period_unit: days
test_period_years: 1
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/train-less-year-log-pct/2025-10-12_18-18-26_MSFT_1h_fm_split_2023-01-01_train_41d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.680560142942136e-05
  mae: 0.004074064951251023
  rmse: 0.006066762021821967
  mape: 603344496358.731
  smape: 169.89536940424475
  mean_directional_accuracy: 49.371428571428574
