experiment_config_name: 2025-11-20_17-37-02_MSFT_1h_fm_split_2023-01-01_train_32d_test_1y_horizon_1
run_timestamp: 2025-11-20_17-37-02
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 32
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/train-less-year-log-pct/2025-11-20_17-37-02_MSFT_1h_fm_split_2023-01-01_train_32d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.677441509203404e-05
  mae: 0.004072971030209046
  rmse: 0.006064191214995948
  mape: 761665833382.1931
  smape: 169.32768022393867
  mean_directional_accuracy: 48.97142857142857
