experiment_config_name: 2025-11-20_17-26-21_MSFT_1h_fm_split_2023-01-01_train_25d_test_1y_horizon_1
run_timestamp: 2025-11-20_17-26-21
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/train-less-year-log-pct/2025-11-20_17-26-21_MSFT_1h_fm_split_2023-01-01_train_25d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.689344604001375e-05
  mae: 0.004079010714106753
  rmse: 0.006073997533751043
  mape: 790695959534.0265
  smape: 169.6505485560353
  mean_directional_accuracy: 49.2
