experiment_config_name: 2025-11-20_18-30-30_MSFT_1h_fm_split_2023-01-01_train_116d_test_1y_horizon_1
run_timestamp: 2025-11-20_18-30-30
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 116
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/train-less-year-log-pct/2025-11-20_18-30-30_MSFT_1h_fm_split_2023-01-01_train_116d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.664228158155519e-05
  mae: 0.004063228659738343
  rmse: 0.006053286841176056
  mape: 542157873516.87524
  smape: 170.84553886550572
  mean_directional_accuracy: 47.714285714285715
