experiment_config_name: 2025-11-30_11-11-43_MSFT_1h_chronos_base_split_2022-03-31_train_75d_test_60d_horizon_1
run_timestamp: 2025-11-30_11-11-43
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 75
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: chronos_base
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/chronos_base/rq3-market-downturn-2022-linear/2025-11-30_11-11-43_MSFT_1h_chronos_base_split_2022-03-31_train_75d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.398135433244082
  mae: 1.9551855915348701
  rmse: 2.5294535839275807
  mape: 0.7060236816854619
  smape: 0.7077874703457954
  mean_directional_accuracy: 100.0
