experiment_config_name: 2025-09-09_02-26-11_MSFT_1h_sundial_split_2023-01-01_train_175d_test_1y_horizon_1
run_timestamp: 2025-09-09_02-26-11
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/sundial/train-less-year-linear/2025-09-09_02-26-11_MSFT_1h_sundial_split_2023-01-01_train_175d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.600117426999565
  mae: 1.3233852064732146
  rmse: 1.8973975405801402
  mape: 0.42689529500180556
