experiment_config_name: 2025-09-29_02-08-48_MSFT_1h_sundial_split_2023-01-01_train_200d_test_1y_horizon_1
run_timestamp: 2025-09-29_02-08-48
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/sundial/train-less-year-linear/2025-09-29_02-08-48_MSFT_1h_sundial_split_2023-01-01_train_200d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.587772828736366
  mae: 1.3253574012974334
  rmse: 1.8941417129497904
  mape: 0.4275055895659262
