experiment_config_name: 2025-09-29_01-30-07_MSFT_1h_sundial_split_2023-01-01_train_50d_test_1y_horizon_1
run_timestamp: 2025-09-29_01-30-07
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 50
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/sundial/train-less-year-linear/2025-09-29_01-30-07_MSFT_1h_sundial_split_2023-01-01_train_50d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.6279042486675794
  mae: 1.3168778902762281
  rmse: 1.9047058168304047
  mape: 0.42753797413706673
