experiment_config_name: 2025-11-19_12-25-46_MSFT_1h_sundial_split_2023-01-01_train_225d_test_1y_horizon_1
run_timestamp: 2025-11-19_12-25-46
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 225
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/train-less-year-linear/2025-11-19_12-25-46_MSFT_1h_sundial_split_2023-01-01_train_225d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.6136188461533685
  mae: 1.3286999382672995
  rmse: 1.9009520893892535
  mape: 0.4285604378861172
  smape: 0.42909326428326
  mean_directional_accuracy: 100.0
