experiment_config_name: 2025-09-09_02-33-30_MSFT_1h_sundial_split_2023-01-01_train_200d_test_1y_horizon_1
run_timestamp: 2025-09-09_02-33-30
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2023-01-01'
training_period_value: 200
training_period_unit: days
test_period_years: 1
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1h/sundial/train-less-year-linear/2025-09-09_02-33-30_MSFT_1h_sundial_split_2023-01-01_train_200d_test_1y_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 3.5651788946211944
  mae: 1.319259007045201
  rmse: 1.888168131979034
  mape: 0.4256912237359356
