experiment_config_name: 2025-11-30_09-54-44_MSFT_1h_sundial_split_2020-02-28_train_193d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-54-44
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 193
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-log/2025-11-30_09-54-44_MSFT_1h_sundial_split_2020-02-28_train_193d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.955180266536569
  mae: 1.8014220872407178
  rmse: 2.6372675758323365
  mape: 1.1605992733843957
  smape: 1.1604709397129838
  mean_directional_accuracy: 100.0
