experiment_config_name: 2025-11-30_09-54-00_MSFT_1h_sundial_split_2020-02-28_train_149d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-54-00
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 149
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-covid-crash-2020-log/2025-11-30_09-54-00_MSFT_1h_sundial_split_2020-02-28_train_149d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 6.934546576569641
  mae: 1.7917704150901024
  rmse: 2.633352725437601
  mape: 1.1535867695057416
  smape: 1.1535134663885867
  mean_directional_accuracy: 100.0
