experiment_config_name: 2025-11-30_09-55-28_MSFT_1h_sundial_split_2020-02-28_train_249d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-55-28
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 249
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-covid-crash-2020-log/2025-11-30_09-55-28_MSFT_1h_sundial_split_2020-02-28_train_249d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.015591820324293
  mae: 1.8215093015876795
  rmse: 2.6486962491618953
  mape: 1.17297325123621
  smape: 1.173273837139749
  mean_directional_accuracy: 100.0
