experiment_config_name: 2025-11-30_09-51-14_MSFT_1h_sundial_split_2020-02-28_train_53d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-51-14
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 53
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-covid-crash-2020-log/2025-11-30_09-51-14_MSFT_1h_sundial_split_2020-02-28_train_53d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.270287860785783
  mae: 1.8204559985436632
  rmse: 2.6963471328420945
  mape: 1.1748881488931755
  smape: 1.1726850775259503
  mean_directional_accuracy: 100.0
