experiment_config_name: 2025-11-30_09-33-38_MSFT_1h_arima_split_2022-03-31_train_250d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-33-38
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2022-03-31'
training_period_value: 250
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: arima
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/arima/rq3-market-downturn-2022-linear-pct/2025-11-30_09-33-38_MSFT_1h_arima_split_2022-03-31_train_250d_test_60d_horizon_1.csv
arima_order: (0, 0, 0)
evaluation_metrics:
  mse: 6.355447878933332e-05
  mae: 0.005896828322278409
  rmse: 0.007972106295661975
  mape: 100.0
  smape: 200.0
  mean_directional_accuracy: 0.0
