experiment_config_name: 2025-11-16_23-18-36_MSFT_1d_naive_split_2023-01-01_train_175d_test_1y_horizon_63
run_timestamp: 2025-11-16_23-18-36
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 175
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: naive
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/naive/train-less-year-linear/2025-11-16_23-18-36_MSFT_1d_naive_split_2023-01-01_train_175d_test_1y_horizon_63.csv
arima_order: N/A
evaluation_metrics:
  mse: 875.3398092000004
  mae: 23.242680000000004
  rmse: 29.586142181771528
  mape: 7.168005402371539
  smape: 7.5568118549217616
  mean_directional_accuracy: 100.0
