experiment_config_name: 2025-11-17_01-09-27_MSFT_1d_arima_split_2023-01-01_train_6y_test_1y_horizon_63
run_timestamp: 2025-11-17_01-09-27
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 6.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/arima/train-restricted-years/2025-11-17_01-09-27_MSFT_1d_arima_split_2023-01-01_train_6y_test_1y_horizon_63.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 718.6108691560833
  mae: 21.766211385621528
  rmse: 26.80691830770712
  mape: 6.692047599637154
  smape: 6.9634326864287885
  mean_directional_accuracy: 100.0
