experiment_config_name: 2025-11-17_01-05-51_MSFT_1d_arima_split_2023-01-01_train_5y_test_1y_horizon_21
run_timestamp: 2025-11-17_01-05-51
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 5.0
training_period_unit: years
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 21
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1d/arima/train-restricted-years/2025-11-17_01-05-51_MSFT_1d_arima_split_2023-01-01_train_5y_test_1y_horizon_21.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 184.48305576693727
  mae: 9.96693090095611
  rmse: 13.582453967046503
  mape: 3.1736060095835636
  smape: 3.249344858962224
  mean_directional_accuracy: 100.0
