experiment_config_name: 2025-09-28_17-36-04_MSFT_1d_arima_split_2023-01-01_train_7y_test_1y_horizon_1
run_timestamp: 2025-09-28_17-36-04
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 7.0
training_period_unit: years
test_period_years: 1
forecasting_method: arima
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/arima/train-restricted-years/2025-09-28_17-36-04_MSFT_1d_arima_split_2023-01-01_train_7y_test_1y_horizon_1.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 22.662362513205412
  mae: 3.643332294307504
  rmse: 4.760500237706686
  mape: 1.2094524125222788
