experiment_config_name: 2025-09-28_17-40-11_MSFT_1d_arima_split_2023-01-01_train_8y_test_1y_horizon_63
run_timestamp: 2025-09-28_17-40-11
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 8.0
training_period_unit: years
test_period_years: 1
forecasting_method: arima
horizon_length: 63
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/arima/train-restricted-years/2025-09-28_17-40-11_MSFT_1d_arima_split_2023-01-01_train_8y_test_1y_horizon_63.csv
arima_order: (1, 1, 1)
evaluation_metrics:
  mse: 732.5709764276417
  mae: 21.77841180664589
  rmse: 27.06604840806359
  mape: 6.789654328300449
