experiment_config_name: 2025-11-30_09-59-41_MSFT_1h_sundial_split_2008-01-20_train_150d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-59-41
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 150
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-financial-crisis-2008-linear/2025-11-30_09-59-41_MSFT_1h_sundial_split_2008-01-20_train_150d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.08272471552594078
  mae: 0.1875509704696176
  rmse: 0.28761904583309633
  mape: 0.6335658379518644
  smape: 0.6325243888197027
  mean_directional_accuracy: 100.0
