experiment_config_name: 2025-11-30_09-56-53_MSFT_1h_sundial_split_2008-01-20_train_50d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-56-53
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 50
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1h/sundial/rq3-financial-crisis-2008-linear/2025-11-30_09-56-53_MSFT_1h_sundial_split_2008-01-20_train_50d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.0884456072849109
  mae: 0.19593891183673715
  rmse: 0.2973980620059769
  mape: 0.6603196197804985
  smape: 0.658734389573373
  mean_directional_accuracy: 100.0
