experiment_config_name: 2025-11-30_09-56-14_MSFT_1h_sundial_split_2008-01-20_train_25d_test_60d_horizon_1
run_timestamp: 2025-11-30_09-56-14
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 25
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: sundial
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/thesis-code-new/results/MSFT/1h/sundial/rq3-financial-crisis-2008-linear/2025-11-30_09-56-14_MSFT_1h_sundial_split_2008-01-20_train_25d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 0.08925400694957492
  mae: 0.19657386992451198
  rmse: 0.2987540911009838
  mape: 0.6622531173815489
  smape: 0.6609258916058608
  mean_directional_accuracy: 100.0
