experiment_config_name: 2025-11-30_18-53-54_MSFT_1h_fm_split_2008-01-20_train_200d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-53-54
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 200
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/rq3-financial-crisis-2008-linear-pct/2025-11-30_18-53-54_MSFT_1h_fm_split_2008-01-20_train_200d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 8.525191623226698e-05
  mae: 0.005920642730756478
  rmse: 0.009233196425521716
  mape: 3136282595563.4907
  smape: 169.12110122899503
  mean_directional_accuracy: 49.47735191637631
