experiment_config_name: 2025-11-30_18-44-42_MSFT_1h_fm_split_2008-01-20_train_25d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-44-42
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 25
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/thesis-code-new/results/MSFT/1h/fm/rq3-financial-crisis-2008-linear-pct/2025-11-30_18-44-42_MSFT_1h_fm_split_2008-01-20_train_25d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 8.64593281441457e-05
  mae: 0.005963204570896355
  rmse: 0.009298350829267828
  mape: 4959530285958.101
  smape: 163.04680099751826
  mean_directional_accuracy: 52.961672473867594
