experiment_config_name: 2025-11-30_18-48-38_MSFT_1h_fm_split_2008-01-20_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-48-38
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2008-01-20'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: true
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/rq3-financial-crisis-2008-linear-pct/2025-11-30_18-48-38_MSFT_1h_fm_split_2008-01-20_train_100d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 8.488193159145471e-05
  mae: 0.005891757315992982
  rmse: 0.00921313907370635
  mape: 4968089424565.923
  smape: 163.8086845490457
  mean_directional_accuracy: 51.21951219512195
