experiment_config_name: 2025-09-28_17-39-49_MSFT_1d_arima_split_2023-01-01_train_125d_test_1y_horizon_21
run_timestamp: 2025-09-28_17-39-49
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 21
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/arima/train-less-year-linear/2025-09-28_17-39-49_MSFT_1d_arima_split_2023-01-01_train_125d_test_1y_horizon_21.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 1426.0585914421101
  mae: 31.61593287438088
  rmse: 37.763190959479445
  mape: 9.761021367686581
