experiment_config_name: 2025-11-17_01-30-41_MSFT_1d_arima_split_2023-01-01_train_25d_test_1y_horizon_63
run_timestamp: 2025-11-17_01-30-41
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 25
training_period_unit: days
test_period_value: 1
test_period_unit: years
forecasting_method: arima
horizon_length: 63
differencing_applied: false
percentage_change_applied: false
results_file_path: /Users/dimitris/LU/Thesis/Thesis-Master-Repo/msc-thesis-stock-forecasting/results/MSFT/1d/arima/train-less-year-linear/2025-11-17_01-30-41_MSFT_1d_arima_split_2023-01-01_train_25d_test_1y_horizon_63.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 2482.604634786902
  mae: 43.083677486544595
  rmse: 49.825742691774316
  mape: 13.083786458653982
  smape: 14.265789362476415
  mean_directional_accuracy: 100.0
