experiment_config_name: 2025-09-17_16-43-59_MSFT_1d_arima_split_2023-01-01_train_125d_test_1y_horizon_1
run_timestamp: 2025-09-17_16-43-59
ticker: MSFT
timefreq: 1d
target_column: Open
split_date: '2023-01-01'
training_period_value: 125
training_period_unit: days
test_period_years: 1
forecasting_method: arima
horizon_length: 1
differencing_applied: false
results_file_path: /Users/dimitris/LU/Thesis/thesis-code-new/results/MSFT/1d/arima/train-less-year-linear/2025-09-17_16-43-59_MSFT_1d_arima_split_2023-01-01_train_125d_test_1y_horizon_1.csv
arima_order: (1, 0, 0)
evaluation_metrics:
  mse: 36.17567737511751
  mae: 4.753626472042641
  rmse: 6.014621964439454
  mape: 1.5497827561868618
