experiment_config_name: 2025-11-30_18-02-34_MSFT_1h_fm_split_2020-02-28_train_225d_test_60d_horizon_1
run_timestamp: 2025-11-30_18-02-34
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 225
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/rq3-covid-crash-2020-linear/2025-11-30_18-02-34_MSFT_1h_fm_split_2020-02-28_train_225d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.494978641956414
  mae: 1.890073491006778
  rmse: 2.737695863670107
  mape: 1.2133668969212275
  smape: 1.215339448429695
  mean_directional_accuracy: 100.0
