experiment_config_name: 2025-11-30_17-55-58_MSFT_1h_fm_split_2020-02-28_train_100d_test_60d_horizon_1
run_timestamp: 2025-11-30_17-55-58
ticker: MSFT
timefreq: 1h
target_column: Open
split_date: '2020-02-28'
training_period_value: 100
training_period_unit: days
test_period_value: 60
test_period_unit: days
forecasting_method: fm
horizon_length: 1
differencing_applied: false
percentage_change_applied: false
results_file_path: /root/msc-thesis-stock-forecasting/results/MSFT/1h/fm/rq3-covid-crash-2020-linear/2025-11-30_17-55-58_MSFT_1h_fm_split_2020-02-28_train_100d_test_60d_horizon_1.csv
arima_order: N/A
evaluation_metrics:
  mse: 7.406014708320696
  mae: 1.8943009241615856
  rmse: 2.721399402572268
  mape: 1.21700563971597
  smape: 1.21398745325266
  mean_directional_accuracy: 100.0
